/* SVS cost protocol 28. Shared pure calculations: browser, worker and Apps Script. */
var Cost028 = (()=>{
 const groups={weaned:{label:'สุกรหย่านม',unit:'บาท/ตัว',products:['ลูกสุกร'],den:19},fatten:{label:'สุกรขุน',unit:'บาท/กก.',products:['สุกรขุน','สุกรขุน OMEGA'],den:20},gdu:{label:'GDU',unit:'บาท/กก.',products:['สุกรขุน','สุกรขุน OMEGA','สุกรขุน-รุ่นพันธุ์'],den:20}};
 const headers={0:'YEAR',1:'MONTH',5:'LV1_Name',7:'LV2_Name',11:'Org_Name',17:'Product_Name',18:'TYPE',19:'จำนวนหมูดี(ตัว)',20:'น้ำหนักหมูดี(กก.)',24:'ค่ายา (บาท)',33:'ต้นทุนหมูตาย (บาท)',34:'ต้นทุนหมูคัดทิ้ง (บาท)',35:'รายได้คัดทิ้ง (บาท)',42:'ค่าวัคซีน',45:'ค่ายา'};
 const nums={head:19,weight:20,medvac:24,dead:33,cull:34,revenue:35,vac:42,med:45};
 function assert(c,m){if(!c)throw Error(m);}
 function period(name){const m=String(name).match(/^Pivot_COST_(\d{2})(\d{2})(?:[_ -].*)?\.(xlsb|xlsx)$/i);assert(m&&+m[2]>=1&&+m[2]<=12,'ชื่อไฟล์ต้องเป็น Pivot_COST_YYMM.xlsb หรือ .xlsx');return {year:2500+Number(m[1])-543,month:Number(m[2])};}
 function rawNumber(v,row,key){if(v==null||v==='')return null;assert(typeof v==='number'&&Number.isFinite(v),'แถว '+row+' ช่อง '+key+' ไม่ใช่ตัวเลข');return v;}
 function readPivot(aoa,name){const p=period(name);assert(aoa.length>1,'ชีต DATA ไม่มีข้อมูล');Object.keys(headers).forEach(k=>assert(aoa[0][k]===headers[k],'โครงสร้างเปลี่ยน: คอลัมน์ '+(+k+1)+' ต้องเป็น '+headers[k]));
  const out=[],periods=new Set();let maxYear=0,maxMonth=0;
  aoa.slice(1).forEach((r,i)=>{if(r.every(x=>x==null||x===''))return;const year=Number(r[0]),month=Number(r[1]);assert(Number.isInteger(year)&&year>=2000&&year<=2100&&Number.isInteger(month)&&month>=1&&month<=12,'ปี/เดือนผิดที่แถว '+(i+2));if(year>maxYear){maxYear=year;maxMonth=month;}else if(year===maxYear)maxMonth=Math.max(maxMonth,month);periods.add(year+'-'+month);
   if(r[18]!=='INT')return;if(!Object.values(groups).some(g=>g.products.includes(r[17])))return;
   const x={sourceRow:i+2,org:String(r[10]||r[11]||'').trim(),name:String(r[11]||'').trim(),year,month,product:String(r[17]),bu:String(r[5]||''),sourceRegion:String(r[7]||'')};assert(x.org&&x.name,'ไม่มีรหัส/ชื่อฟาร์ม แถว '+(i+2));Object.entries(nums).forEach(([k,c])=>{const v=rawNumber(r[c],i+2,k);x[k]=v===null&&!['head','weight'].includes(k)?0:v;});out.push(x);
  });assert(maxYear===p.year&&maxMonth===p.month,'เดือนล่าสุดใน DATA ไม่ตรงชื่อไฟล์');assert(out.length,'ไม่พบข้อมูล INT ของกลุ่มที่ใช้');const rows=aoa.slice(1).filter(r=>r.some(x=>x!=null&&x!==''));const orgs=[...new Map(rows.map(r=>[String(r[10]),{org:String(r[10]),name:String(r[11]),region:String(r[7])}])).values()];return {period:p,periods:[...periods],source:out,orgs,scan:{total:rows.length,int:rows.filter(r=>r[18]==='INT').length,selected:out.length,otherType:rows.filter(r=>r[18]!=='INT').length,otherProduct:rows.filter(r=>r[18]==='INT').length-out.length}};
 }
 function readKPI(aoa,name){const y=String(name).match(/KPI\s+(\d{2,4})\s/i);assert(y,'ชื่อ KPI ต้องระบุปี เช่น Functional KPI 26 SVS M05.xlsx');let year=+y[1];if(year<100)year+=2000;if(year>2400)year-=543;const h=aoa[0]||[],tc=h.findIndex(v=>String(v).includes('เป้าหมาย')),kc=h.findIndex(v=>String(v).includes('KPI'));assert(tc>=0&&kc>=0,'ไม่พบหัวคอลัมน์ KPI/เป้าหมาย');const targets={},actuals={};
  for(const [g,word] of [['weaned','หย่านม'],['fatten','ขุน']]){targets[g]={};actuals[g]={};for(const [key,kw] of [['medvac','ค่ายาและวัคซีน'],['deadcull','ตายคัดทิ้ง']]){const rs=aoa.slice(1).filter(r=>String(r[kc]).includes(word)&&String(r[kc]).includes(kw));assert(rs.length===1,'แถว KPI '+word+' '+kw+' ต้องมีหนึ่งรายการ');const r=rs[0];assert(typeof r[tc]==='number'&&r[tc]>0,'เป้าหมายต้องมากกว่าศูนย์');targets[g][key]=r[tc];actuals[g][key]=Array.from({length:12},(_,i)=>rawNumber(r[tc+1+i],0,'KPI'));}}targets.gdu={...targets.fatten};return {year,name,targets,actuals};
 }
 function validateSource(x){assert(x&&typeof x.org==='string'&&x.org.length<160&&typeof x.name==='string'&&x.name.length<200,'ข้อมูลฟาร์มไม่ถูกต้อง');assert(Number.isInteger(x.year)&&x.year>=2000&&x.year<=2100&&Number.isInteger(x.month)&&x.month>=1&&x.month<=12,'ปี/เดือนไม่ถูกต้อง');assert(Object.values(groups).some(g=>g.products.includes(x.product)),'ผลิตภัณฑ์ไม่ถูกต้อง');assert(typeof x.bu==='string'&&x.bu.length<150&&typeof x.sourceRegion==='string'&&x.sourceRegion.length<150,'ธุรกิจ/เขตไม่ถูกต้อง');Object.keys(nums).forEach(k=>assert(x[k]===null||typeof x[k]==='number'&&Number.isFinite(x[k]),'ตัวเลข '+k+' ไม่ถูกต้อง'));assert((x.head===null||x.head>=0)&&(x.weight===null||x.weight>=0),'ปริมาณติดลบ');}
 const add=(a,b)=>a===null||b===null?null:a+b;
 function aggregate(source,mapping,gduOrgs){assert(gduOrgs instanceof Set,'ต้องระบุทะเบียน GDU ตามรหัส');const cells=new Map();for(const x of source){validateSource(x);for(const [group,cfg] of Object.entries(groups)){if(!cfg.products.includes(x.product)||group==='fatten'&&gduOrgs.has(x.org)||group==='gdu'&&!gduOrgs.has(x.org))continue;const farmId=mapping[x.org];assert(typeof farmId==='string'&&farmId,'ยังไม่จับคู่ฟาร์ม '+x.name);const key=[x.org,x.year,x.month,group].join('|');let c=cells.get(key);if(!c){c={org:x.org,name:x.name,farmId,year:x.year,month:x.month,group,bu:x.bu,sourceRegion:x.sourceRegion,den:0,medvac:0,vac:0,med:0,deadcull:0,sourceRows:0};cells.set(key,c);}assert(c.bu===x.bu&&c.sourceRegion===x.sourceRegion,'รหัสฟาร์มเดียวกันมีธุรกิจ/เขตต่างกันในเดือนเดียว: '+x.name);c.den=add(c.den,x[cfg.den===19?'head':'weight']);for(const k of ['medvac','vac','med'])c[k]=add(c[k],x[k]);c.deadcull=add(c.deadcull,add(add(x.dead,x.cull),x.revenue));c.sourceRows++;}}
 return [...cells.values()];}
 function sum(rows){if(!rows.length)return null;let o={den:0,medvac:0,deadcull:0,vac:0,med:0};for(const r of rows)for(const k of Object.keys(o))o[k]=add(o[k],r[k]);return o;}
 function rates(rows){const a=sum(rows);const o={den:a?.den??null};for(const k of ['medvac','deadcull','vac','med'])o[k]=a&&a.den>0&&a[k]!==null?a[k]/a.den:null;o.other=o.medvac!==null&&o.med!==null&&o.vac!==null?o.medvac-o.med-o.vac:null;return o;}
 function index(v,t){return t&&t.medvac>0&&t.deadcull>0&&v.medvac!==null&&v.deadcull!==null&&v.medvac>=0&&v.deadcull>=0?100*(.6*v.deadcull/t.deadcull+.4*v.medvac/t.medvac):null;}
 function category(v,t){if(!t||!(t.medvac>0)||!(t.deadcull>0)||v.medvac===null||v.deadcull===null||v.medvac<0||v.deadcull<0)return 'unknown';return v.deadcull>t.deadcull?(v.medvac>t.medvac?'red':'orange'):(v.medvac>t.medvac?'yellow':'green');}
 function compare(a,b,dir='desc'){const x=a.index,y=b.index;if(x===null||y===null)return x===y?String(a.name).localeCompare(String(b.name),'th'):x===null?1:-1;return (dir==='asc'?1:-1)*(x-y)||String(a.name).localeCompare(String(b.name),'th');}
 function merge(oldRows,newRows,periods){const covered=new Set(periods);return oldRows.filter(r=>!covered.has(r.year+'-'+r.month)).concat(newRows);}
 function qc(rows,kpi){const warnings=[],errors=[],diffs=[];for(const group of ['weaned','fatten'])for(const metric of ['medvac','deadcull']){let max=0,n=0;for(let m=1;m<=12;m++){const actual=kpi.actuals?.[group]?.[metric]?.[m-1];if(!(actual>0))continue;const v=rates(rows.filter(r=>r.year===kpi.year&&r.month===m&&r.group===group))[metric];if(v==null)continue;const diff=Math.abs(v-actual)/actual*100;max=Math.max(max,diff);n++;}diffs.push({group,metric,max,months:n});if(!n)warnings.push('ไม่มีผล KPI ให้เทียบ '+groups[group].label+' '+metric);else if(max>1.5)(group==='weaned'?errors:warnings).push(groups[group].label+' '+metric+' ต่าง KPI สูงสุด '+max.toFixed(2)+'%'+(group==='fatten'?' (ขอบเขต GDU ต่างกัน)':''));}
 for(const g of Object.keys(groups)){const fs=new Map();for(const r of rows.filter(r=>r.year===kpi.year&&r.group===g)){if(!fs.has(r.farmId))fs.set(r.farmId,[]);fs.get(r.farmId).push(r);}for(const metric of ['medvac','deadcull']){const vals=[...fs].map(([id,r])=>({id,v:rates(r)[metric]})),sorted=vals.map(x=>x.v).filter(v=>v!==null&&v>0).sort((a,b)=>a-b),n=sorted.length,med=n?(sorted[Math.floor((n-1)/2)]+sorted[Math.floor(n/2)])/2:0;const out=vals.filter(x=>med>0&&x.v>3*med);if(out.length)warnings.push(groups[g].label+' '+metric+' สูงกว่า 3 เท่ามัธยฐาน '+out.length+' ฟาร์ม');}}
 const missing=rows.filter(r=>r.den===null||r.den<=0||r.medvac===null||r.deadcull===null).length;if(missing)warnings.push('ข้อมูลไม่ครบ/ปริมาณเป็นศูนย์ '+missing+' รายการ — เว้นดัชนี ไม่แทนด้วยศูนย์');const negative=rows.filter(r=>['medvac','vac','med','deadcull'].some(k=>r[k]!==null&&r[k]<0));if(negative.length)warnings.push('รายการต้นทุนติดลบ/ปรับปรุงบัญชี '+negative.length+' รายการ — เก็บค่าต้นฉบับและเว้นการจัดกลุ่มหากผลสุทธิติดลบ');warnings.push('GDU ใช้เป้าสุกรขุน ยังไม่มีผล KPI แยกให้เทียบ');return {warnings,errors,diffs};}
 return {groups,headers,period,readPivot,readKPI,aggregate,rates,sum,index,category,compare,merge,qc,validateSource};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=Cost028;
