/* SVS v0.1.33-r1 — maps and farm profile; no private coordinates in static assets. */
'use strict';
const GEO033={board:false,districts:null,promise:null,contexts:{},zoom:{x:0,y:0,w:400,h:680},masterToken:''};
function geoOptions033(ctx){const o=GEO033.contexts[ctx]??=({area:'province',points:true,mode:ctx==='disease'?'general':'open',basis:ctx==='disease'?'history':'current',onlyOpen:false,diseases:[],provinces:[],districts:[],farms:[],areaColor:'#b9dcd0',pointColor:'#176b67',openColor:'#b32235',herdDisease:'PRRS',herdColors:{Unstable:'#9c1831','Stable Active':'#db8735','Stable Inactive':'#d0b426',FreePRRS:'#19734b'}});if(ctx==='disease'){o.provinces=[];o.districts=[];o.farms=[];}return o;}
function geoNorm033(s){return String(s||'').trim().replace(/^(จังหวัด|จ\.|อำเภอ|อ\.|เขต)\s*/,'').replace(/\s/g,'');}
function geoDistrictKey033(p,d){const province=daProvince022(p);let district=geoNorm033(d);if(district==='เมือง')district+=province;return province+'|'+district;}
async function geoLoad033(){if(GEO033.districts)return GEO033.districts;if(GEO033.promise)return GEO033.promise;GEO033.promise=fetch('./map-data/districts033.json?v=39').then(r=>{if(!r.ok)throw Error('โหลดขอบเขตอำเภอไม่สำเร็จ');return r.json();}).then(ds=>{GEO033.districts=ds;return ds;}).catch(e=>{GEO033.promise=null;throw e;});return GEO033.promise;}
function geoTime033(v){return new Date(v).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});}
function geoKnown033(v){return v!==''&&v!==null&&v!==undefined&&Number.isFinite(Number(v));}
function geoValid033(lat,lng){return geoKnown033(lat)&&geoKnown033(lng)&&+lat>=5&&+lat<=21&&+lng>=97&&+lng<=106;}
function geoContains033(p,lat,lng){if(!p._rings){p._rings=p.path.split('Z').filter(Boolean).map(r=>[...r.matchAll(/([\d.]+),([\d.]+)/g)].map(m=>[+m[1],+m[2]]));const pts=p._rings.flat();p._box=[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1])),Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))];}const x=(+lng-96.5)*40,y=(21.5-+lat)*40,b=p._box;if(x<b[0]||x>b[2]||y<b[1]||y>b[3])return false;let hit=false;for(const ring of p._rings)for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [a,c]=ring[i],[d,e]=ring[j];if((c>y)!==(e>y)&&x<(d-a)*(y-c)/(e-c)+a)hit=!hit;}return hit;}
function geoAreaKey033(r){if(!GEO033.districts)return geoDistrictKey033(r.province,r.district);const exact=GEO033.districts.filter(d=>geoDistrictKey033(d.province,d.name)===geoDistrictKey033(r.province,r.district));if(exact.length===1)return exact[0].id;if(r.valid){const candidates=GEO033.districts.filter(d=>(!r.province||daProvince022(d.province)===daProvince022(r.province))&&geoContains033(d,r.lat,r.lng));if(candidates.length===1)return candidates[0].id;}return '';}
function geoCases033(ctx){return ctx==='disease'?daSelected021():state.records.filter(r=>r.type==='event'&&r.status==='ACTIVE').map(r=>({id:r.id,farmId:r.farmId,sourceFarmId:r.farmId,disease:r.data.disease,date:r.data.detectedAt,closedAt:r.data.closedAt||'',status:r.data.closedAt?'closed':'open'}));}
function geoRows033(ctx){const o=geoOptions033(ctx),events=geoCases033(ctx).filter(e=>!o.diseases.length||o.diseases.includes(e.disease));let farms=ctx==='disease'?daData021.farms.filter(f=>events.some(e=>e.farmId===f.id)):visibleFarms();const current=new Map(state.farms.map(f=>[f.id,f]));farms=farms.filter(f=>!o.farms.length||o.farms.includes(f.id));const out=[];
 for(let farm of farms){farm=ctx==='disease'?{...(current.get(farm.id)||{}),...farm}:{...farm,...(current.get(farm.id)||{})};let cases=events.filter(e=>e.farmId===farm.id),open=cases.filter(e=>!e.closedAt&&e.status!=='closed');if(o.onlyOpen&&!open.length)continue;if(o.diseases.length&&!cases.length)continue;
  if(ctx==='disease'&&o.basis==='history'&&o.mode==='general'){const groups=new Map();for(const e of cases){const key=[e.lat,e.lng,e.province,e.district].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e);}for(const list of groups.values()){const e=list[0];out.push({farm,cases:list,open:list.filter(e=>!e.closedAt&&e.status!=='closed'),lat:e.lat,lng:e.lng,province:e.province||'',district:e.district||'',coordinateBasis:e.coordinateBasis||'พิกัดเหตุการณ์',valid:geoValid033(e.lat,e.lng)});}}
  else out.push({farm,cases,open,lat:farm.lat,lng:farm.lng,province:farm.province||'',district:farm.district||'',coordinateBasis:'ตำแหน่งฟาร์มปัจจุบัน',valid:farm.geoStatus!=='REVIEW'&&geoValid033(farm.lat,farm.lng)});
 }
 out.forEach(r=>r.province=daProvince022(r.province));return out.filter(r=>(!o.provinces.length||o.provinces.includes(r.province))&&(!o.districts.length||o.districts.includes(geoDistrictKey033(r.province,r.district))));}
function geoState033(r,o){return uiHerdLatest032(r.farm.id,o.herdDisease)?.data.state||'ยังไม่ระบุ';}
function geoColor033(rows,o,area=false){if(o.mode==='open')return rows.some(r=>r.open.length)?o.openColor:(area?o.areaColor:o.pointColor);if(o.mode==='herd'){const states=[...new Set(rows.map(r=>geoState033(r,o)))];return states.length===1?(o.herdColors[states[0]]||'#70828a'):'#776a97';}return area?o.areaColor:o.pointColor;}
function geoLegend033(rows,o){if(o.mode==='open')return [[o.openColor,'มีเคสเปิดอยู่'],[o.pointColor,'ไม่มีเคสเปิดของโรคที่เลือก'],[o.areaColor,'พื้นที่ที่มีฟาร์ม ไม่มีเคสเปิด']];if(o.mode==='herd')return [...new Set(rows.map(r=>geoState033(r,o)))].map(s=>[o.herdColors[s]||'#70828a',s]).concat([['#776a97','หลายสถานะในพื้นที่']]);return [[o.areaColor,'พื้นที่ที่มีข้อมูล'],[o.pointColor,'ตำแหน่งฟาร์ม']];}
function geoDescription033(ctx){const o=geoOptions033(ctx),parts=[ctx==='disease'?daFilterText021():[values016(region).join(' / ')||'ทุกภาค',farmTypeFilterText023(layer),search?'ค้นหา: '+search:''].filter(Boolean).join(' · '),'ชื่อโรค: '+(o.diseases.length?o.diseases.join(' / '):ctx==='disease'?daMapDiseaseText023():'ทุกโรค'),o.mode==='herd'?'สถานะฝูง '+o.herdDisease:o.mode==='open'?'เคสโรคที่ยังเปิดอยู่':'ข้อมูลที่ตั้ง',o.basis==='history'&&ctx==='disease'&&o.mode==='general'?'พิกัดตามประวัติเหตุการณ์ / ตามที่มาบันทึก':'ตำแหน่งฟาร์มปัจจุบัน'];if(o.provinces.length)parts.push('จังหวัด: '+o.provinces.join(' / '));if(o.districts.length)parts.push('อำเภอ: '+o.districts.map(x=>x.split('|')[1]).join(' / '));if(o.farms.length)parts.push('ฟาร์ม: '+o.farms.map(id=>state.farms.find(f=>f.id===id)?.name||daData021?.farms.find(f=>f.id===id)?.name||id).join(' / '));if(o.onlyOpen)parts.push('เฉพาะฟาร์มมีเคสเปิด');return parts.join(' · ');}
function geoSVG033(ctx,rows=geoRows033(ctx)){const o=geoOptions033(ctx),areas=o.area==='district'?(GEO033.districts||[]):PROVINCES022,groups=new Map(),keys=r=>o.area==='district'?geoAreaKey033(r):daProvince022(r.province);rows.forEach(r=>{const k=keys(r);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);});const z=GEO033.zoom,clusters=[];rows.filter(r=>r.valid).forEach(r=>{const x=(+r.lng-96.5)*40,y=(21.5-+r.lat)*40;const group=clusters.find(g=>Math.hypot(g.x-x,g.y-y)<10*z.w/400);if(group){group.rows.push(r);}else clusters.push({x,y,rows:[r]});});const grouped=new Map(clusters.map((g,i)=>[i,g.rows]));
 return `<svg class="geo-svg033" viewBox="${z.x} ${z.y} ${z.w} ${z.h}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="แผนที่ฟาร์มประเทศไทย"><rect x="0" y="0" width="400" height="680" fill="white"/>${areas.map(p=>{const key=o.area==='district'?p.id:daProvince022(p.name),list=groups.get(key)||[],n=new Set(list.map(r=>r.farm.id)).size;return `<path d="${p.path}" fill="${o.area!=='none'&&n?geoColor033(list,o,true):'#f2f5f5'}" fill-rule="evenodd" stroke="#9cafaa" stroke-width=".35" vector-effect="non-scaling-stroke" ${n?`data-geo-area033="${esc(key)}" role="button" tabindex="0" aria-label="${esc(p.name)} ${n} ฟาร์ม"`:''}><title>${esc(p.province?p.province+' / ':'')}${esc(p.name)} · ${n} ฟาร์ม</title></path>`;}).join('')}${o.points?[...grouped.values()].map((list,i)=>`<g data-geo-point033="${i}" data-geo-ids033="${esc(JSON.stringify(list.map(r=>[r.farm.id,r.lat,r.lng])))}" role="button" tabindex="0" aria-label="${esc(list.map(r=>r.farm.name).join(' / '))}"><circle cx="${(+list[0].lng-96.5)*40}" cy="${(21.5-+list[0].lat)*40}" r="${(list.length>1?7:3.5)*z.w/400}" fill="${geoColor033(list,o)}" stroke="white" stroke-width=".9" vector-effect="non-scaling-stroke"/>${list.length>1?`<text x="${(+list[0].lng-96.5)*40}" y="${(21.5-+list[0].lat)*40}" text-anchor="middle" dominant-baseline="central" fill="white" font-family="sans-serif" font-size="${8*z.w/400}" pointer-events="none">${new Set(list.map(r=>r.farm.id)).size}</text>`:''}<title>${esc(list.map(r=>r.farm.name).join(' / '))} · ${list.reduce((n,r)=>n+r.open.length,0)} เคสเปิด</title></g>`).join(''):''}</svg>`;}
// Disease facet counts ignore the local disease choice, but retain the main filters.
function geoDiseaseCounts039(){
 const o=geoOptions033('disease'),farmIds=new Set(daData021.farms.map(f=>f.id)),groups=new Map();
 for(const e of geoCases033('disease')){if(!farmIds.has(e.farmId))continue;const name=e.disease||'';if(!groups.has(name))groups.set(name,new Map());groups.get(name).set(e.id,e);}
 return [...groups].map(([name,byId])=>{let events=[...byId.values()];if(o.onlyOpen){const openFarms=new Set(events.filter(e=>!e.closedAt&&e.status!=='closed').map(e=>e.farmId));events=events.filter(e=>openFarms.has(e.farmId));}return {name,count:events.length};}).filter(x=>x.count).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'th'));
}
function geoDiseaseTable039(){
 const o=geoOptions033('disease'),items=geoDiseaseCounts039();
 return `<aside class="geo-disease-list039"><div class="geo-disease-heading039"><h3>โรคและจำนวนเคส</h3><button type="button" class="geo-all039 da-only-screen021 ${o.diseases.length?'':'primary'}" data-geo-all039 aria-pressed="${!o.diseases.length}">ทุกโรค</button></div><p class="geo-disease-caption039">จำนวนเคสตามตัวกรองหลัก${o.onlyOpen?' · เฉพาะฟาร์มมีเคสเปิดของโรคนั้น':''}</p><table class="geo-disease-table039"><thead><tr><th scope="col">ชื่อโรค</th><th scope="col">เคส</th></tr></thead><tbody>${items.map(({name,count})=>{const selected=!o.diseases.length||o.diseases.includes(name);return `<tr class="${selected?'geo-selected039':''}"><td><button type="button" class="geo-disease-choice039" data-geo-disease039="${esc(name)}" aria-pressed="${selected}"><span class="geo-disease-check039" aria-hidden="true">${selected?'✓':''}</span><span>${esc(name||'ไม่ระบุชื่อโรค')}</span></button></td><td>${count.toLocaleString('th-TH')}</td></tr>`;}).join('')||'<tr><td colspan="2" class="geo-empty039">ไม่พบเคส</td></tr>'}</tbody></table><small class="da-only-screen021 geo-disease-caption039">เลือกชื่อโรคได้หลายรายการ</small></aside>`;
}
function geoInfo039(ctx,rows){
 const o=geoOptions033(ctx),missing=new Set(rows.filter(r=>!r.valid).map(r=>r.farm.id)).size;
 return `<aside class="geo-info033"><b>${new Set(rows.map(r=>r.farm.id)).size} ฟาร์ม</b><p>${new Set(rows.flatMap(r=>r.open.map(e=>e.id))).size} เคสเปิดอยู่</p>${missing?`<small>${missing} ฟาร์มยังไม่มีพิกัดพร้อมแสดง</small>`:''}<div class="geo-legend033">${geoLegend033(rows,o).map(([c,l])=>`<div><i style="background:${c}"></i>${esc(l)}</div>`).join('')}</div>${o.mode==='open'&&o.area!=='none'?'<small>สีพื้นที่หมายถึงมีฟาร์มที่มีเคสเปิดอยู่ในพื้นที่</small>':''}<p class="geo-data-at033">ข้อมูล ณ ${esc(geoTime033(ctx==='disease'?daData021.loadedAt:state.settings.loadedAt||today()))}</p></aside>`;
}
function geoPanel033(ctx){
 const o=geoOptions033(ctx),rows=geoRows033(ctx),isDisease=ctx==='disease',tools=`<button data-geo-options033>ตัวกรองและรูปแบบแผนที่</button><details class="ui-export032"><summary>ส่งออกแผนที่ ▾</summary><div class="ui-menu032"><button data-geo-export033="png">ภาพ PNG</button><button data-geo-export033="pdf">PDF</button></div></details>`,canvas=`<div class="geo-canvas033">${o.area==='district'&&!GEO033.districts?'<p role="status">กำลังโหลดขอบเขตอำเภอ…</p>':geoSVG033(ctx,rows)}</div>`,info=geoInfo039(ctx,rows);
 return `<section class="panel geo-panel033 ${isDisease?'geo-disease-panel039':''}" data-geo-context033="${ctx}"><div class="panelhead"><h2>${isDisease?'แผนที่การเกิดโรค':'แผนที่ฟาร์ม'}</h2>${isDisease?'':`<div class="geo-tools033 da-only-screen021">${tools}</div>`}</div><div class="geo-tools033 da-only-screen021">${[['none','แบบจุด'],['district','แบบอำเภอ'],['province','แบบจังหวัด']].map(([v,t])=>`<button data-geo-area-mode033="${v}" class="${o.area===v?'primary':''}">${t}</button>`).join('')}<label><input type="checkbox" data-geo-points033 ${o.points?'checked':''}> จุดฟาร์ม</label><button data-geo-zoom033="in" aria-label="ซูมเข้า">+</button><button data-geo-zoom033="out" aria-label="ซูมออก">-</button><button data-geo-zoom033="reset">ประเทศไทย</button>${isDisease?tools:''}</div><p class="geo-scope033">${esc(geoDescription033(ctx))}</p><div class="geo-map-layout033">${isDisease?info+canvas+geoDiseaseTable039():canvas+info}</div><small class="geo-credit033">จังหวัด: geoBoundaries / © OpenStreetMap contributors (ODbL), 2017 · อำเภอ: Royal Thai Survey Department / OCHA ROAP ผ่าน geoBoundaries, 2019 (CC BY 3.0 IGO)</small></section>`;
}
function geoRerender033(ctx){ctx==='disease'?daRender021():render();}
function geoBind033(ctx){const host=document.querySelector(`[data-geo-context033="${ctx}"]`);if(!host)return;const o=geoOptions033(ctx);if(ctx==='disease'){host.querySelector('[data-geo-all039]').onclick=()=>{o.diseases=[];geoRerender033(ctx);document.querySelector('[data-geo-all039]')?.focus({preventScroll:true});};host.querySelectorAll('[data-geo-disease039]').forEach(b=>b.onclick=()=>{const name=b.dataset.geoDisease039;o.diseases=o.diseases.includes(name)?o.diseases.filter(x=>x!==name):[...o.diseases,name];geoRerender033(ctx);[...document.querySelectorAll('[data-geo-disease039]')].find(x=>x.dataset.geoDisease039===name)?.focus({preventScroll:true});});}host.querySelector('[data-geo-options033]').onclick=()=>geoDrawer033(ctx);host.querySelectorAll('[data-geo-export033]').forEach(b=>b.onclick=()=>geoExport033(ctx,b.dataset.geoExport033));host.querySelector('[data-geo-points033]').onchange=e=>{o.points=e.target.checked;geoRerender033(ctx);};host.querySelectorAll('[data-geo-area-mode033]').forEach(b=>b.onclick=()=>{o.area=b.dataset.geoAreaMode033;if(o.area==='none')o.points=true;geoRerender033(ctx);});if(o.area==='district'&&!GEO033.districts)geoLoad033().then(()=>{if(document.querySelector(`[data-geo-context033="${ctx}"]`))geoRerender033(ctx);}).catch(e=>{const target=host.querySelector('.geo-canvas033');if(target){target.innerHTML='<p>โหลดขอบเขตอำเภอไม่สำเร็จ</p><button>ลองใหม่</button>';target.querySelector('button').onclick=()=>geoRerender033(ctx);}toast(e.message);});
 host.querySelectorAll('[data-geo-zoom033]').forEach(b=>b.onclick=()=>{const z=GEO033.zoom,k=b.dataset.geoZoom033;if(k==='reset')Object.assign(z,{x:0,y:0,w:400,h:680});else{const scale=k==='in'?.7:1/.7,w=Math.max(25,Math.min(400,z.w*scale)),h=w*1.7;Object.assign(z,{x:z.x+(z.w-w)/2,y:z.y+(z.h-h)/2,w,h});}geoRerender033(ctx);});
 const rows=geoRows033(ctx),click=(el,fn)=>{el.onclick=fn;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();fn();}};};host.querySelectorAll('[data-geo-area033]').forEach(el=>click(el,()=>geoPopup033(rows.filter(r=>(o.area==='district'?geoAreaKey033(r):daProvince022(r.province))===el.dataset.geoArea033),o.area==='district'?(GEO033.districts.find(d=>d.id===el.dataset.geoArea033)?.name||'อำเภอ'):el.dataset.geoArea033)));host.querySelectorAll('[data-geo-point033]').forEach(el=>click(el,()=>{const keys=JSON.parse(el.dataset.geoIds033);geoPopup033(rows.filter(r=>keys.some(k=>k[0]===r.farm.id&&String(k[1])===String(r.lat)&&String(k[2])===String(r.lng))),'ข้อมูลฟาร์ม');}));
 const svg=host.querySelector('svg');if(svg){let drag=null,moved=false;svg.onpointerdown=e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,z:{...GEO033.zoom}};moved=false;};svg.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)<7)return;moved=true;svg.setPointerCapture(e.pointerId);const box=svg.getBoundingClientRect(),factor=Math.max(drag.z.w/box.width,drag.z.h/box.height);GEO033.zoom.x=drag.z.x-dx*factor;GEO033.zoom.y=drag.z.y-dy*factor;svg.setAttribute('viewBox',`${GEO033.zoom.x} ${GEO033.zoom.y} ${GEO033.zoom.w} ${GEO033.zoom.h}`);};svg.onpointerup=()=>{drag=null;};svg.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopImmediatePropagation();moved=false;}},true);}}
function geoPopup033(rows,title){const farms=[...new Map(rows.map(r=>[r.farm.id,r.farm])).values()],ids=new Set(rows.flatMap(r=>r.open.map(e=>e.id)));modal(title,`<p>${farms.length} ฟาร์ม · ${ids.size} เคสเปิดอยู่</p><div class="tablewrap"><table><thead><tr><th>ฟาร์ม</th><th>ที่ตั้ง</th><th>เคสเปิด / โรค</th><th></th></tr></thead><tbody>${farms.map(f=>{const items=rows.filter(r=>r.farm.id===f.id),cases=[...new Map(items.flatMap(r=>r.open).map(e=>[e.id,e])).values()];return `<tr><td>${esc(f.name)}</td><td>${esc(items[0].province+' / '+items[0].district)}<small>${esc(items[0].coordinateBasis)}</small></td><td>${cases.length} · ${esc([...new Set(cases.map(e=>e.disease))].join(' / '))}</td><td><button data-geo-open033="${esc(f.id)}">ดูรายละเอียดฟาร์ม</button></td></tr>`;}).join('')}</tbody></table></div>`);$$('[data-geo-open033]').forEach(b=>b.onclick=()=>{const id=b.dataset.geoOpen033;if(!state.farms.some(f=>f.id===id)){toast('ฟาร์มประวัติ: เปิดจากรายการเคสในหน้าข้อมูลการเกิดโรค');return;}$('#modal').close();uiGo032(()=>{daActive021=false;adminData=null;currentFarm=id;tab='profile';render();});});}
function geoDrawer033(ctx){const o=geoOptions033(ctx),farms=ctx==='disease'?daData021.farms.filter(f=>daSelected021().some(e=>e.farmId===f.id)):visibleFarms(),ps=[...new Set(farms.map(f=>state.farms.find(c=>c.id===f.id)?.province||f.province).map(daProvince022).filter(Boolean))].sort(),ds=[...new Set(farms.map(f=>{f=state.farms.find(c=>c.id===f.id)||f;return f.district?geoDistrictKey033(f.province,f.district):'';}).filter(Boolean))].sort(),diseases=[...new Set(geoCases033(ctx).map(e=>e.disease))].sort(),rows=geoRows033(ctx),states=[...new Set(rows.map(r=>geoState033(r,o)))];
 const d=uiDrawer032('ตัวกรองและรูปแบบแผนที่',`<label>การลงสี<select id="geoMode033">${[['general','สีทั่วไป'],['open','ตามเคสโรคที่ยังเปิดอยู่'],['herd','ตามสถานะฝูง']].map(([v,l])=>`<option value="${v}" ${o.mode===v?'selected':''}>${l}</option>`).join('')}</select></label>${ctx==='disease'?`<label>ตำแหน่งที่ใช้<select id="geoBasis033"><option value="history" ${o.basis==='history'?'selected':''}>พิกัดตามประวัติเหตุการณ์ (โหมดสีทั่วไป)</option><option value="current" ${o.basis==='current'?'selected':''}>ตำแหน่งฟาร์มปัจจุบัน</option></select></label>`:''}<label><input type="checkbox" id="geoOnly033" ${o.onlyOpen?'checked':''}> เฉพาะฟาร์มที่มีเคสเปิดอยู่</label><p class="muted">ไม่เลือก = ทุกค่า</p><button type="button" id="geoClear033">ล้างตัวกรองแผนที่</button><h3>ชื่อโรค</h3>${uiChecks032('geoDiseases',diseases.map(x=>[x,x]),o.diseases)}${ctx==='disease'?'':`<h3>จังหวัด</h3>${uiChecks032('geoProvinces',ps.map(x=>[x,x]),o.provinces)}<h3>อำเภอ</h3>${uiChecks032('geoDistricts',ds.map(x=>[x,x.replace('|',' / ')]),o.districts)}<h3>ฟาร์ม</h3><input type="search" id="geoFarmSearch033" placeholder="ค้นหาฟาร์ม">${uiChecks032('geoFarms',farms.map(f=>[f.id,f.name]),o.farms)}`}<h3>สีแผนที่</h3>${[['areaColor','พื้นที่'],['pointColor','จุดฟาร์ม'],['openColor','มีเคสเปิด']].map(([k,l])=>`<label class="geo-color033">${l}<input type="color" data-geo-color033="${k}" value="${o[k]}"></label>`).join('')}<h3>สถานะฝูง</h3><label>โรค<select id="geoHerd033">${['PRRS','PED','FMD'].map(x=>`<option ${o.herdDisease===x?'selected':''}>${x}</option>`).join('')}</select></label>${states.map(s=>`<label class="geo-color033">${esc(s)}<input type="color" data-geo-herd-color033="${esc(s)}" value="${o.herdColors[s]||'#70828a'}"></label>`).join('')}`,el=>{o.mode=el.querySelector('#geoMode033').value;o.onlyOpen=el.querySelector('#geoOnly033').checked;o.basis=el.querySelector('#geoBasis033')?.value||'current';o.herdDisease=el.querySelector('#geoHerd033').value;for(const [k,id] of [['diseases','geoDiseases'],['provinces','geoProvinces'],['districts','geoDistricts'],['farms','geoFarms']])o[k]=uiChecked032(el,id);el.querySelectorAll('[data-geo-color033]').forEach(i=>o[i.dataset.geoColor033]=i.value);el.querySelectorAll('[data-geo-herd-color033]').forEach(i=>o.herdColors[i.dataset.geoHerdColor033]=i.value);geoRerender033(ctx);});d.querySelector('#geoClear033').onclick=()=>{d.querySelectorAll('[data-check032]').forEach(i=>i.checked=false);d.querySelector('#geoOnly033').checked=false;};if(d.querySelector('#geoFarmSearch033'))d.querySelector('#geoFarmSearch033').oninput=e=>d.querySelectorAll('[data-check032="geoFarms"]').forEach(i=>i.parentElement.hidden=!i.parentElement.textContent.includes(e.target.value));}
const geoDashboard033=dashboard;
dashboard=function(){geoDashboard033();if(!$('#app .controls'))return;const b=document.createElement('button');b.id='geoView033';b.className=GEO033.board?'primary':'';b.textContent=GEO033.board?'ดูรายชื่อฟาร์ม':'ดูแผนที่';($('#app .controls [data-filter="prrs"]')?.parentElement||$('#app .controls')).append(b);b.onclick=()=>uiGo032(()=>{GEO033.board=!GEO033.board;render();});if(GEO033.board){const board=$('#app .balanced-board')||$('#app > .panel.empty');if(board)board.outerHTML=geoPanel033('farm');else $('#app').insertAdjacentHTML('beforeend',geoPanel033('farm'));geoBind033('farm');if($('#exportPNG'))$('#exportPNG').onclick=()=>geoExport033('farm','png');if($('#exportPDF'))$('#exportPDF').onclick=()=>geoExport033('farm','pdf');}uiRemember032();};
const geoSnapshot033=uiSnapshot032,geoRestore033=uiRestore032;
uiSnapshot032=function(){return {...geoSnapshot033(),geo:{board:GEO033.board,contexts:uiClone032(GEO033.contexts),zoom:{...GEO033.zoom}}};};
uiRestore032=async function(s){if(s.geo){GEO033.board=s.geo.board;GEO033.contexts=uiClone032(s.geo.contexts);GEO033.zoom={...s.geo.zoom};}return geoRestore033(s);};
const geoLogin033=loginView;loginView=function(){GEO033.board=false;GEO033.contexts={};GEO033.zoom={x:0,y:0,w:400,h:680};return geoLogin033();};
const geoDAContent033=daContent021,geoDARender033=daRender021;
DA_TABS021.splice(DA_TABS021.length-1,0,['causes','สาเหตุและความเสี่ยง']);
daContent021=function(events){if(daView021==='map')return geoPanel033('disease')+daRegionBreakdown023([...new Map(geoRows033('disease').flatMap(r=>r.cases).map(e=>[e.id,e])).values()]);if(daView021==='causes')return geoRisks033(events);return geoDAContent033(events);};
daRender021=function(){geoDARender033();if(daView021==='map'){geoBind033('disease');$('#daReload021').onclick=loadRefresh;}if(daView021==='causes'){const k=$('#daCapture021 .da-kpis021');k?.previousElementSibling?.matches('p.muted')&&k.previousElementSibling.remove();k?.remove();geoRiskBind033();}};
const geoDAExport033=daExportFilters021;daExportFilters021=function(){return {...geoDAExport033(),map:uiClone032(geoOptions033('disease')),mapViewport:{...GEO033.zoom}};};
function geoRiskData033(events){const keys=['cause','risk1','risk2','risk3'],counts=new Map(),missing=[0,0,0,0];for(const e of events)keys.forEach((k,i)=>{const p=e.pathways?.[k]||{},text=String(p.details||e.introduction?.[k]||'').trim(),cat=p.category||(PATH_CATS015.includes(text)?text:text?'ยังไม่จัดประเภท':'');if(!cat){missing[i]++;return;}if(!counts.has(cat))counts.set(cat,[0,0,0,0]);counts.get(cat)[i]++;});return {keys,missing,rows:[...counts].sort((a,b)=>b[1].reduce((x,y)=>x+y,0)-a[1].reduce((x,y)=>x+y,0))};}
function geoRisks033(events){const d=geoRiskData033(events),labels=['สาเหตุ','ความเสี่ยงที่ 1','ความเสี่ยงที่ 2','ความเสี่ยงที่ 3'];return `<section class="panel"><h2>สรุปสาเหตุและความเสี่ยง</h2><p>${events.length} เคสตามตัวกรอง · นับแยกแต่ละอันดับ ไม่มีการถ่วงน้ำหนัก</p><div class="tablewrap"><table><thead><tr><th>ประเภทช่องทาง</th>${labels.map(t=>`<th>${t} (เคส)</th>`).join('')}</tr></thead><tbody>${d.rows.map(([cat,c])=>`<tr><th>${esc(cat)}</th>${c.map((n,i)=>`<td>${n?`<button class="da-link021" data-risk-cat033="${esc(cat)}" data-risk-key033="${d.keys[i]}">${n}</button>`:''}</td>`).join('')}</tr>`).join('')}<tr><th>ยังไม่มีข้อมูล</th>${d.missing.map(n=>`<td>${n||''}</td>`).join('')}</tr></tbody></table></div></section><div class="da-grid021">${labels.map((label,i)=>{const rows=d.rows.filter(r=>r[1][i]).sort((a,b)=>b[1][i]-a[1][i]),max=Math.max(1,...rows.map(r=>r[1][i]));return `<section class="panel"><h2>${label}</h2><div class="geo-risk-bars033">${rows.map(([cat,c])=>`<div><span>${esc(cat)}</span><div class="geo-risk-track033"><i style="width:${100*c[i]/max}%;background:${['#176b67','#527fa0','#a77b35','#856785'][i]}"></i></div><b>${c[i]}</b></div>`).join('')||'<p class="muted">ยังไม่มีข้อมูล</p>'}</div></section>`;}).join('')}</div>`;}
function geoRiskBind033(){$$('[data-risk-cat033]').forEach(b=>b.onclick=()=>{const key=b.dataset.riskKey033,cat=b.dataset.riskCat033,list=daSelected021().filter(e=>{const p=e.pathways?.[key]||{},t=p.details||e.introduction?.[key]||'';return (p.category||(PATH_CATS015.includes(t.trim())?t.trim():t?'ยังไม่จัดประเภท':''))===cat;});modal(cat,daCaseTable021(list)+`<h3>รายละเอียดต้นฉบับ</h3>${list.map(e=>`<p><b>${esc(daFarm021(e.farmId).name)} · ${esc(e.date)}</b><br>${esc(e.pathways?.[key]?.other||'')} ${esc(e.pathways?.[key]?.details||e.introduction?.[key]||'')}</p>`).join('')}`);daBindCaseButtons021();});}
async function geoExport033(ctx,format){if(ctx==='disease')return geoDiseaseExport039(format);const o=geoOptions033(ctx);if(o.area==='district'&&!GEO033.districts){toast('รอขอบเขตอำเภอโหลดครบก่อนส่งออก');return;}const rows=geoRows033(ctx),svg=geoSVG033(ctx,rows),legend=geoLegend033(rows,o),scope=geoDescription033(ctx),title=ctx==='disease'?'แผนที่การเกิดโรค':'แผนที่ฟาร์ม',extra={filters:ctx==='disease'?daExportFilters021():{regions:values016(region),types:values016(layer),search,vet:values016(selectedVet018),map:uiClone032(o),mapViewport:{...GEO033.zoom}}};const w=format==='pdf'?window.open('','_blank'):null;if(format==='pdf'&&!w)return toast('กรุณาอนุญาตหน้าต่างใหม่');if(w)w.document.write('<meta charset="utf-8"><p>กำลังเตรียมรายงาน…</p>');try{const meta=await exportIdentity016(ctx==='disease'?'diseaseAnalytics':'overview',format,extra),at=ctx==='disease'?daData021.loadedAt:state.settings.loadedAt||today(),count=new Set(rows.map(r=>r.farm.id)).size;if(format==='pdf'){w.document.open();w.document.write(`<!doctype html><html lang="th"><meta charset="utf-8"><title>${esc(title+' '+meta.id)}</title><style>${REPORT_STYLE015}@page{size:A4 landscape;margin:8mm;@bottom-right{content:none}}body{font-family:'TH Sarabun New',Tahoma;color:#20383d;font-size:11pt!important;line-height:1.25!important;max-width:none!important;margin:0!important;padding:0!important}h1{font-size:20pt!important;margin:0 0 2mm!important;padding:2mm 4mm!important}p{font-size:11pt;margin:3mm 0}.map{display:flex;gap:12mm;align-items:center;break-inside:avoid}.map svg{height:130mm;width:170mm}.legend{font-size:11pt;max-width:70mm}.legend div{margin-bottom:3mm}.legend i{display:inline-block;width:4mm;height:4mm;margin-right:2mm}.foot{color:#888;font-size:8pt}.export-attribution016{font-size:8pt!important;margin-top:2mm!important;padding-top:1mm!important}button{margin:5px}@media print{button{display:none}}</style><body><button onclick="print()">พิมพ์ / บันทึก PDF</button><h1>SVS — ${title}</h1><p>${esc(scope)}</p><div class="map">${svg}<div class="legend"><b>${count} ฟาร์ม · ${new Set(rows.flatMap(r=>r.open.map(e=>e.id))).size} เคสเปิด</b>${legend.map(([c,l])=>`<div><i style="background:${c}"></i>${esc(l)}</div>`).join('')}<p>ข้อมูล ณ ${esc(geoTime033(at))}</p>${o.mode==='open'&&o.area!=='none'?'<p>สีพื้นที่หมายถึงมีฟาร์มที่มีเคสเปิดอยู่ในพื้นที่</p>':''}</div></div><div class="foot">จังหวัด: geoBoundaries / © OpenStreetMap (ODbL), 2017 · อำเภอ: RTSD / OCHA ROAP ผ่าน geoBoundaries (CC BY 3.0 IGO), 2019</div>${attributionHTML016(meta)}</body></html>`);w.document.close();return;}
 await document.fonts.ready;const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await img.decode();const canvas=document.createElement('canvas');canvas.width=1600;const c=canvas.getContext('2d');c.font='20px "Noto Sans Thai"';const lines=overviewLines(c,scope,1480),footer=exportLines016(meta).flatMap(t=>overviewLines(c,t,1480));canvas.height=1050+lines.length*30+footer.length*24;c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#123d43';c.font='bold 32px "Noto Sans Thai"';c.fillText('SVS — '+title,50,55);c.font='20px "Noto Sans Thai"';lines.forEach((l,i)=>c.fillText(l,50,95+i*30));const top=115+lines.length*30;c.drawImage(img,150,top,460,782);c.font='bold 23px "Noto Sans Thai"';c.fillText(count+' ฟาร์ม · '+new Set(rows.flatMap(r=>r.open.map(e=>e.id))).size+' เคสเปิด',760,top+65);c.font='20px "Noto Sans Thai"';legend.forEach(([color,l],i)=>{c.fillStyle=color;c.fillRect(760,top+100+i*40,20,20);c.fillStyle='#20383d';c.fillText(l,795,top+118+i*40);});c.fillText('ข้อมูล ณ '+geoTime033(at),760,top+155+legend.length*40);if(o.mode==='open')c.fillText('สีพื้นที่: มีฟาร์มที่มีเคสเปิดอยู่ในพื้นที่',760,top+195+legend.length*40);c.fillStyle='#788781';c.font='14px "Noto Sans Thai"';c.fillText('จังหวัด: geoBoundaries / © OpenStreetMap (ODbL), 2017 · อำเภอ: RTSD / OCHA ROAP ผ่าน geoBoundaries (CC BY 3.0 IGO), 2019',50,canvas.height-55-footer.length*24);c.font='16px "Noto Sans Thai"';footer.forEach((l,i)=>c.fillText(l,50,canvas.height-30-(footer.length-1-i)*24));const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('สร้างภาพไม่สำเร็จ');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SVS_Map_'+meta.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
 }catch(e){if(w&&!w.closed)w.document.body.textContent=e.message;toast(e.message);}}
const geoFarmForm033=farmForm;farmForm=function(f){geoFarmForm033(f);const form=$('#form'),grid=form.querySelector('.fieldgrid');if(!grid)return;grid.insertAdjacentHTML('beforeend',field('จังหวัด','province',f?.province||'','text',false)+field('อำเภอ','district',f?.district||'','text',false)+field('ความจุแม่พันธุ์ (ตัว)','sowCapacity',f?.sowCapacity??'','number',false)+field('ความจุพ่อพันธุ์ (ตัว)','boarCapacity',f?.boarCapacity??'','number',false)+field('ความจุสุกรขุน (ตัว)','finisherCapacity',f?.finisherCapacity??'','number',false)+field('ความจุ GDU (ตัว)','gduCapacity',f?.gduCapacity??'','number',false)+selectField('สถานะพิกัด','geoStatus',['','VERIFIED','REVIEW'],f?.geoStatus||'',false));};
const geoDetail033=detail;detail=function(){geoDetail033();if(tab!=='profile')return;const f=state.farms.find(f=>f.id===currentFarm),host=$('#detailBody .profilegrid');host?.insertAdjacentHTML('beforeend',[['จังหวัด',f.province],['อำเภอ',f.district],['ความจุแม่พันธุ์ (ตัว)',f.sowCapacity],['ความจุพ่อพันธุ์ (ตัว)',f.boarCapacity],['ความจุสุกรขุน (ตัว)',f.finisherCapacity],['ความจุ GDU (ตัว)',f.gduCapacity]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v===''||v==null?'ยังไม่ระบุ':v)}</b></div>`).join(''));};
const geoRegistry033=uiFarmRegistry032;uiFarmRegistry032=function(){geoRegistry033();if(state.user.role!=='Admin')return;$('#app .pagehead').insertAdjacentHTML('beforeend','<button id="geoMaster033">ทะเบียนรวมใน Sheet</button>');$('#geoMaster033').onclick=geoMasterDialog033;};
async function geoMasterDialog033(){try{const info=await api('farmMaster033',{op:'link'});modal('ทะเบียนฟาร์มรวม',`<p><a href="${esc(info.url)}" target="_blank" rel="noopener">เปิดชีต FarmMaster033</a></p><p>แก้ไขหลายฟาร์มในชีต แล้วกดตรวจการเปลี่ยนแปลงก่อนนำไปใช้</p><button id="geoMasterRefresh033">ดึงทะเบียนล่าสุดเข้าชีต</button> <button id="geoMasterPreview033">ตรวจการเปลี่ยนแปลง</button><div id="geoMasterResult033"></div><details><summary>เริ่มฉบับแก้ไขใหม่</summary><p>เก็บสำเนาฐานข้อมูลรวมฉบับแก้ไขค้างไว้ก่อน แล้วดึงทะเบียนล่าสุดมาแทนฉบับในชีตนี้</p><button id="geoMasterRebuild033">สำรองฉบับค้างและดึงทะเบียนใหม่</button></details>`);$('#geoMasterRebuild033').onclick=async()=>{const b=$('#geoMasterRebuild033');b.disabled=true;try{const r=await api('farmMaster033',{op:'rebuild'});$('#geoMasterResult033').innerHTML='<p>ดึงทะเบียนล่าสุดแล้ว · สำรองฉบับค้าง: <a target="_blank" rel="noopener" href="https://drive.google.com/file/d/'+encodeURIComponent(r.backup)+'/view">เปิดสำเนา</a></p>';}catch(e){toast(e.message);}finally{b.disabled=false;}};$('#geoMasterRefresh033').onclick=async()=>{try{await api('farmMaster033',{op:'refresh'});toast('ดึงทะเบียนล่าสุดแล้ว');}catch(e){toast(e.message);}};$('#geoMasterPreview033').onclick=async()=>{try{const p=await api('farmMaster033',{op:'preview'});GEO033.masterToken=p.token;$('#geoMasterResult033').innerHTML=`<p>${p.changes.length} ฟาร์มที่แก้ไข</p>${p.errors.map(e=>`<p class="error">${esc(e)}</p>`).join('')}<ul>${p.changes.map(c=>`<li>${esc(c.name)}: ${esc(c.fields.join(', '))}</li>`).join('')}</ul>${!p.errors.length&&p.changes.length?'<button id="geoMasterApply033" class="primary">บันทึกการเปลี่ยนแปลงเข้าระบบ</button>':''}`;if($('#geoMasterApply033'))$('#geoMasterApply033').onclick=async()=>{const b=$('#geoMasterApply033');b.disabled=true;try{const result=await api('farmMaster033',{op:'apply',token:GEO033.masterToken});$('#modal').close();await refresh();toast('บันทึก '+result.updated+' ฟาร์มแล้ว');}catch(e){b.disabled=false;toast(e.message);}};}catch(e){toast(e.message);}};}catch(e){toast(e.message);}}
const GEO_PRINT039=`
.da-report021 h1{background:none!important;border:0!important;color:#203d45!important;padding:0!important;margin:0 0 3mm!important}
.da-report021 .geo-disease-panel039 h2{border:0;padding:0;margin:0 0 2mm;color:#203d45}
.geo-disease-panel039{background:#fff;break-inside:avoid}
.geo-disease-panel039 .geo-map-layout033{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.6fr) minmax(0,1.2fr);gap:5mm;align-items:center}
.geo-disease-panel039 .geo-canvas033{width:auto;height:125mm;min-height:0;max-height:none}
.geo-svg033{display:block;width:100%;height:100%}
.geo-info033{font-size:10pt}.geo-info033>b{font-size:22pt;color:#123d43}.geo-info033 p{font-size:10pt;margin:3mm 0}.geo-info033 small,.geo-data-at033{font-size:9pt;color:#76848a}
.geo-legend033{margin:6mm 0}.geo-legend033>div{display:flex;gap:2mm;align-items:center;margin:3mm 0}.geo-legend033 i{display:block;width:4mm;height:4mm;flex:none;border-radius:1mm}
.geo-disease-heading039 h3{margin:0 0 2mm;font-size:12pt}.geo-disease-caption039{color:#647c7f;font-size:8pt!important;margin:1mm 0 3mm}
.geo-disease-table039{width:100%;table-layout:fixed;border-collapse:collapse;font-size:10pt!important}
.geo-disease-table039 th,.geo-disease-table039 td{border:0!important;border-bottom:1px solid #e0e9e8!important;padding:2mm!important;text-align:left;background:white;overflow-wrap:anywhere}
.geo-disease-table039 th{background:#eff5f4!important;font-weight:600}.geo-disease-table039 th:last-child,.geo-disease-table039 td:last-child{width:16mm!important;text-align:right;font-variant-numeric:tabular-nums}
.geo-disease-table039 .geo-selected039 td{background:#e9f4f1!important;color:#135f5b;font-weight:600}
.geo-disease-choice039{display:flex;gap:2mm;align-items:center;color:inherit;font:inherit;background:none;border:0;padding:0}.geo-disease-check039{width:3mm;flex:none}
.geo-credit033{display:block;font-size:7pt;color:#82918e;margin-top:2mm}.geo-scope033{font-size:9pt;color:#526e72;line-height:1.5;margin:2mm 0}
.da-only-screen021{display:none!important}
@media print{.da-report021 #footer021{position:static!important;margin-top:2mm!important}.da-report021 #footer021 .export-attribution016{break-inside:avoid}}
`;
function geoExportSnapshot039(){
 const node=document.createElement('div');node.innerHTML=geoPanel033('disease');node.querySelectorAll('.da-only-screen021').forEach(x=>x.remove());node.querySelectorAll('button').forEach(b=>{const span=document.createElement('span');span.className=b.className;span.innerHTML=b.innerHTML;b.replaceWith(span);});return node.innerHTML;
}
async function geoRaster039(svg){
 const box=svg.getBoundingClientRect(),v=svg.viewBox.baseVal,ratio=v.width/v.height,width=Math.min(box.width,box.height*ratio),height=width/ratio;
 const img=new Image();img.className='geo-svg033';img.width=width;img.height=height;img.style.setProperty('width',width+'px','important');img.style.setProperty('height',height+'px','important');img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg.outerHTML);await img.decode();svg.replaceWith(img);return img;
}
let geoExportBusy039=false;
async function geoDiseaseExport039(format){
 if(geoExportBusy039)return;const o=geoOptions033('disease');if(o.area==='district'&&!GEO033.districts)return toast('รอขอบเขตอำเภอโหลดครบก่อนส่งออก');
 const snapshot=geoExportSnapshot039(),filters=daExportFilters021();
 if(format==='pdf')return printPanel021('SVS — แผนที่การเกิดโรค',snapshot,'diseaseAnalytics',{filters});
 geoExportBusy039=true;let clone;
 try{
  const meta=await exportIdentity016('diseaseAnalytics','png',{filters});clone=document.createElement('div');clone.className='geo-export039';clone.innerHTML='<h1>SVS — แผนที่การเกิดโรค</h1>'+snapshot+attributionHTML016(meta);Object.assign(clone.style,{position:'absolute',left:'-20000px',top:'0',width:'1600px',padding:'32px',background:'white',boxSizing:'border-box'});document.body.appendChild(clone);
  for(const svg of clone.querySelectorAll('svg'))await geoRaster039(svg);
  await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
  const rect=clone.getBoundingClientRect(),width=Math.ceil(rect.width),height=Math.ceil(rect.height),scale=Math.min(1.5,16000/width,16000/height,Math.sqrt(40000000/(width*height)));if(scale<.6)throw Error('ข้อมูลยาวเกินไปสำหรับภาพเดียว กรุณาเลือกโรคหรือใช้ PDF');
  const c=document.createElement('canvas');c.width=Math.ceil(width*scale);c.height=Math.ceil(height*scale);const g=c.getContext('2d');g.scale(scale,scale);g.fillStyle='white';g.fillRect(0,0,width,height);paintOverviewBoard(g,clone,0,0);
  const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('สร้างภาพไม่สำเร็จ');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SVS_Map_'+meta.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);
 }catch(e){toast(e.message);}finally{clone?.remove();geoExportBusy039=false;}
}
const geoPrintPanel033=printPanel021;
printPanel021=function(title,body,report,extra={}){if(report==='diseaseAnalytics'&&daView021==='map')body='<style>'+GEO_PRINT039+'</style>'+body;if(report==='diseaseAnalytics'&&daView021==='causes')body='<style>.geo-risk-bars033>div{display:flex;align-items:center;gap:12px;margin:12px 0}.geo-risk-bars033 span{width:150px}.geo-risk-track033{width:220px;height:16px;background:#eef3f1}.geo-risk-track033 i{display:block;height:100%}</style>'+body;return geoPrintPanel033(title,body,report,extra);};
start();
