/* SVS 0.1.32: navigation, scoped controls and on-demand views. */
'use strict';
var UI032={uid:'',entries:[],at:-1,restoring:false,adminView:'home',herd:'PRRS',exportPick:false,corePromise:null,run:Date.now().toString(36)+Math.random().toString(36).slice(2)};
const UI_CP_KEYS032=['view','group','year','from','to','regions','bus','types','farm','search','exclude','sort','listOrder','targetYear','table','groupBy','bars','chart','composition','colors','streak','compareMode032','compareBasis035'];
function uiClone032(v){return JSON.parse(JSON.stringify(v));}
function uiSnapshot032(){return {filter,disease,prrsState,search,region,layer,currentFarm,tab,currentRegion018,regionTab018,orgMode010,prrsView012,prrsLayer012,prrsSearch012,selectedVet018,showTeamFilter018,showCancelled,eventKind011,eventDisplay022,daActive021,daView021,daFilters021:uiClone032(daFilters021),daPrice021,daMapMode022,daRegionList023,daTimelineMode027,admin:!!adminData,adminView:UI032.adminView,teamSelected:UI032.teamSelected||'',herd:UI032.herd,pa:uiClone032(paView024),pp:uiClone032(ppView026),labYear,labMode,labSample017,cp:Object.fromEntries(UI_CP_KEYS032.map(k=>[k,uiClone032(CP028[k]??null)])),off:[...CP028.off],scroll:window.scrollY};}
function uiRemember032(){if(UI032.at>=0&&!UI032.restoring)UI032.entries[UI032.at]=uiSnapshot032();}
function uiHistoryStart032(){const uid=state.user?.id;if(!uid)return;if(UI032.uid!==uid){UI032.uid=uid;UI032.entries=[];UI032.at=0;UI032.entries[0]=uiSnapshot032();history.replaceState({svs032:true,uid,run:UI032.run,index:0},'',location.pathname+location.search);}}
function uiPush032(){if(!state.user)return;uiHistoryStart032();uiRemember032();UI032.entries.splice(UI032.at+1);UI032.at++;UI032.entries[UI032.at]=uiSnapshot032();history.pushState({svs032:true,uid:UI032.uid,run:UI032.run,index:UI032.at},'',location.pathname+location.search);}
function uiGo032(fn){if(CP028.busy||saveBusy){toast('กรุณารอการบันทึกให้เสร็จก่อนเปลี่ยนหน้า');return;}uiPush032();UI032.exportPick=false;fn();window.scrollTo(0,0);}
function uiBack032(){if(CP028.busy||saveBusy)return toast('กรุณารอการบันทึกให้เสร็จก่อนย้อนกลับ');if(UI032.at>0)history.back();else uiMain032('farms');}
async function uiRestore032(s){UI032.restoring=true;try{({filter,disease,prrsState,search,region,layer,currentFarm,tab,currentRegion018,regionTab018,orgMode010,prrsView012,prrsLayer012,prrsSearch012,selectedVet018,showTeamFilter018,showCancelled,eventKind011,eventDisplay022,daActive021,daView021,daPrice021,daMapMode022,daRegionList023,daTimelineMode027,labYear,labMode,labSample017}=s);daFilters021=uiClone032(s.daFilters021);paView024=uiClone032(s.pa);ppView026=uiClone032(s.pp);Object.assign(CP028,uiClone032(s.cp));CP028.off=new Set(s.off);UI032.adminView=s.adminView;UI032.teamSelected=s.teamSelected;UI032.herd=s.herd;UI032.exportPick=false;adminData=s.admin&&state.user.role==='Admin'?(UI032.adminCache||await api('adminData')):null;render();requestAnimationFrame(()=>window.scrollTo(0,s.scroll));}finally{UI032.restoring=false;}}
window.addEventListener('popstate',e=>{if(!e.state?.svs032||e.state.uid!==state.user?.id||e.state.run!==UI032.run)return;if(CP028.busy||saveBusy||document.querySelector('dialog[open]')){const delta=UI032.at-e.state.index;if(delta)history.go(delta);if(delta&&document.querySelector('dialog[open]'))toast('กรุณาปิดหน้าต่างข้อมูลก่อนย้อนกลับ');return;}uiRemember032();UI032.at=e.state.index;const s=UI032.entries[UI032.at];if(s)uiRestore032(s);});
window.addEventListener('scroll',()=>{if(!UI032.restoring&&UI032.at>=0&&UI032.entries[UI032.at])UI032.entries[UI032.at].scroll=window.scrollY;},{passive:true});
const UI_NAV_SELECTORS032='[data-farm],[data-cp-farm],[data-cp-view],[data-cp-mode032],[data-tab],[data-da-tab021],[data-team-farm],[data-region-info],[data-region-tab],[data-open-da021],[data-org-mode],[data-pa-parity026],#teamManager019';
document.addEventListener('click',e=>{const el=e.target.closest(UI_NAV_SELECTORS032);if(!el||el.closest('dialog')||el.dataset.uiNav032)return;if(CP028.busy||saveBusy){e.preventDefault();e.stopImmediatePropagation();toast('กรุณารอการบันทึกให้เสร็จก่อนเปลี่ยนหน้า');return;}uiPush032();UI032.exportPick=false;},true);
function uiMain032(key){uiGo032(()=>{currentFarm=null;currentRegion018=null;daActive021=false;adminData=null;if(key==='disease'){filter='';openAnalytics021();}else if(key==='cost'){filter='cost';if(['import','registry','settings'].includes(CP028.view))CP028.view='overview';render();}else if(key==='team'){filter='';currentRegion018='ALL';regionTab018='team';orgMode010='svs';render();}else if(key==='admin'){UI032.adminView='home';filter='';showAdmin();}else{filter='';render();}});}
function uiSection032(){if(adminData||filter==='cost'&&['import','registry','settings'].includes(CP028.view))return 'admin';if(daActive021)return daView021==='rules'&&state.user.role==='Admin'?'admin':'disease';if(currentRegion018)return 'team';if(filter==='cost'&&!currentFarm)return 'cost';return 'farms';}
function uiShell032(){if(!state.user)return;uiHistoryStart032();const nav=document.querySelector('header nav');const section=uiSection032();nav.className='ui-mainnav032';nav.innerHTML=[['farms','ภาพรวมฟาร์ม'],['disease','ข้อมูลการเกิดโรค'],['cost','ประสิทธิภาพและต้นทุน'],['team','ทีมงานสัตวแพทย์'],...(state.user.role==='Admin'?[['admin','จัดการระบบ']]:[])].map(([k,l])=>`<button data-main032="${k}" class="${section===k?'active':''}" aria-current="${section===k?'page':'false'}">${l}</button>`).join('')+'<button id="home" hidden></button><button id="admin" hidden></button>';
 nav.querySelectorAll('[data-main032]').forEach(b=>b.onclick=()=>uiMain032(b.dataset.main032));$('#home').onclick=()=>uiMain032('farms');$('#admin').onclick=()=>uiMain032('admin');document.querySelector('header .brand').onclick=e=>{e.preventDefault();uiMain032('farms');};
 const app=$('#app');app.classList.toggle('ui-export-pick032',UI032.exportPick);app.querySelector('#uiBack032')?.remove();const back=document.createElement('button');back.id='uiBack032';back.className='ui-back032';back.textContent='← ย้อนกลับ';back.disabled=UI032.at===0;back.onclick=uiBack032;app.prepend(back);
 ['back','cpBack','daBack021','regionBack018','ppBack026','tmBack019'].forEach(id=>{const b=$('#'+id);if(b)b.hidden=true;});
 uiExports032();uiRemember032();}
function uiExports032(){const app=$('#app');const groups=[['#cpPNG','#cpPDF'],['#exportPNG','#exportPDF'],['#daPNG021','#daPDF021','#daCSV021'],['[data-prrs-export="png"]','[data-prrs-export="pdf"]'],['#paPNG024','#paPDF024','#ppPDF026'],['#labSummaryPDF019'],['#pigPDF021','#pigCSV021']];for(const group of groups){const buttons=group.map(s=>app.querySelector(s)).filter(Boolean);if(!buttons.length||buttons[0].closest('.ui-export032'))continue;const d=document.createElement('details');d.className='ui-export032 ui-screen032';d.innerHTML='<summary>ส่งออก ▾</summary><div class="ui-menu032"></div>';buttons[0].before(d);const menu=d.lastElementChild;buttons.forEach(b=>{menu.appendChild(b);b.addEventListener('click',()=>{d.open=false;});});const toggle=$('.export-toggle016');if(toggle&&group[0]==='#exportPNG')menu.appendChild(toggle);if(group[0]==='#cpPNG'||group[0]==='#daPNG021'){const b=document.createElement('button');b.textContent=UI032.exportPick?'เสร็จสิ้นการเลือกส่วนส่งออก':'เลือกส่วนที่จะส่งออก';b.onclick=()=>{UI032.exportPick=!UI032.exportPick;app.classList.toggle('ui-export-pick032',UI032.exportPick);b.textContent=UI032.exportPick?'เสร็จสิ้นการเลือกส่วนส่งออก':'เลือกส่วนที่จะส่งออก';d.open=false;};menu.appendChild(b);}}}
function uiDisplay032(container,title='การแสดงผล'){if(!container||container.querySelector(':scope > .ui-display032'))return;const children=[...container.children];if(!children.length)return;const d=document.createElement('details');d.className='ui-display032 ui-screen032';d.innerHTML=`<summary>${title} ▾</summary><div class="ui-menu032"></div>`;children.forEach(c=>d.lastElementChild.appendChild(c));container.appendChild(d);}
function uiDrawer032(title,body,apply){const d=document.createElement('dialog');d.className='ui-drawer032';d.innerHTML=`<form method="dialog"><div class="ui-drawer-head032"><h2>${esc(title)}</h2><button aria-label="ปิดตัวกรอง" value="cancel">✕</button></div></form><div class="ui-drawer-body032">${body}</div><div class="ui-drawer-foot032"><button data-drawer-cancel032>ยกเลิก</button><button class="primary" data-drawer-apply032>ใช้ตัวกรอง</button></div>`;document.body.appendChild(d);d.addEventListener('close',()=>d.remove(),{once:true});d.querySelector('[data-drawer-cancel032]').onclick=()=>d.close();d.querySelector('[data-drawer-apply032]').onclick=()=>{if(apply(d)!==false)d.close();};d.showModal();return d;}
function uiChecks032(key,items,selected){return `<div class="ui-checks032">${items.map(([v,l])=>`<label><input type="checkbox" data-check032="${key}" value="${esc(v)}" ${selected.includes(String(v))?'checked':''}>${esc(l)}</label>`).join('')}</div>`;}
function uiChecked032(d,key){return [...d.querySelectorAll(`[data-check032="${key}"]:checked`)].map(e=>e.value);}
function uiChips032(items){return `<div class="ui-chips032">${items.filter(x=>x[1]).map(([k,l])=>`<button data-clear032="${k}" title="ล้างตัวกรอง ${esc(l)}">${esc(l)} <span aria-hidden="true">×</span></button>`).join('')}</div>`;}
function uiCore032(){if(window.Cost028)return Promise.resolve();if(UI032.corePromise)return UI032.corePromise;UI032.corePromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./cost-core.js?v=35';s.onload=resolve;s.onerror=()=>{UI032.corePromise=null;s.remove();reject(Error('โหลดโมดูลต้นทุนไม่สำเร็จ กรุณาลองใหม่'));};document.head.appendChild(s);});return UI032.corePromise;}
// Cost: use the existing calculation/export engine; only compute the selected view.
CP028.compareMode032='colors';
const uiOldCPReset032=cpReset028;
cpReset028=function(){uiOldCPReset032();CP028.compareMode032='colors';UI032.costFarms=null;};
const cpOriginalRender032=cpRender028,cpOriginalBind032=cpBind028,cpOriginalControls032=cpControls028;
const cpOriginalPanel032=cpPanel028;
cpPanel028=function(key,title,body,tools='',long=false){return cpOriginalPanel032(key,title,body,tools,long);};
cpControls028=function(){const years=[...new Set([CP028.year,...CP028.data.rows.map(r=>r.year)])].sort((a,b)=>b-a);const more=CP028.bus.length+CP028.types.length+CP028.exclude.length+(CP028.targetYear?1:0);return `<section class="panel ui-filterbar032 cp-screen"><div class="ui-filterrow032"><label>ปี<select data-cp="year">${cpOptions028(years.map(y=>[y,y+543]),CP028.year)}</select></label>${CP028.view==='compare'?`<label>ข้อมูล<select data-cp="compareBasis035" aria-label="รายเดือนหรือสะสม">${cpOptions028([['month','รายเดือน'],['cum','สะสม']],CP028.compareBasis035||'month')}</select></label>`:''}<label>ช่วงเดือน<div class="ui-range032"><select data-cp="from" aria-label="ตั้งแต่เดือน">${cpOptions028(CP_MONTHS028.map((m,i)=>[i+1,m]),CP028.from)}</select><span>–</span><select data-cp="to" aria-label="ถึงเดือน">${cpOptions028(CP_MONTHS028.map((m,i)=>[i+1,m]),CP028.to)}</select></div></label>${cpMulti028('regions','ภาค',CP_REGIONS028.map(x=>[x,x]))}<label>กลุ่มการผลิต<select data-cp="group">${cpOptions028(Object.entries(Cost028.groups).map(([k,g])=>[k,g.label]),CP028.group)}</select></label><button id="uiCostMore032" class="${more?'filter-active023':''}">ตัวกรองเพิ่มเติม${more?' · '+more:''}</button><button id="cpResetFilters" class="ui-text032">ล้างตัวกรอง</button></div>${uiChips032([['regions',CP028.regions.join(', ')],['bus',CP028.bus.join(', ')],['types',CP028.types.map(k=>FARM_TYPES023.find(t=>t[0]===k)?.[1]||k).join(', ')],['exclude',CP028.exclude.map(k=>({unstable:'ไม่รวม PRRS Unstable',active:'ไม่รวม PRRS Stable Active',PRRS:'ไม่รวมเคส PRRS ที่เปิด',D1:'ไม่รวมเคส D1 ที่เปิด'})[k]).join(', ')],['targetYear',CP028.targetYear?'KPI ปี '+(CP028.targetYear+543):'']])}</section>`;};
cpExclusions028=function(){return '';};
cpDisplayHTML029=function(){return '';};
cpChartTools028=function(key){const c=cpChartState028(key);return `<label>ข้อมูล<select data-cp-chart="${key}" data-prop="mode">${cpOptions028([['month','รายเดือน'],['cum','สะสม']],c.mode)}</select></label><label>รูปแบบ<select data-cp-chart="${key}" data-prop="kind">${cpOptions028([['bar','กราฟแท่ง'],['line','กราฟเส้น']],c.kind)}</select></label><label class="cp-noexport"><input type="checkbox" data-cp-chart="${key}" data-prop="prev" ${c.prev?'checked':''}>แสดงปีก่อนหน้า</label>`;};
cpHeatTools031=function(){return `<label>ฟาร์มที่แสดง<select data-cp="streak">${cpOptions028([['3','แดง 3 เดือน'],['2','แดง 2 เดือน'],['all','ทุกฟาร์ม']],CP028.streak)}</select></label><label>เรียงตาม Index<select data-cp="sort">${cpOptions028([['desc','สูง → ต่ำ'],['asc','ต่ำ → สูง']],CP028.sort)}</select></label>`;};
cpCompare028=function(){const mode=CP028.compareMode032||'colors';const switcher=`<div class="ui-viewtabs032 cp-screen">${[['colors','กลุ่มสี'],['months','ติดตามรายเดือน'],['ranking','อันดับต้นทุน']].map(([k,l])=>`<button data-cp-mode032="${k}" aria-pressed="${mode===k}" class="${mode===k?'primary':''}">${l}</button>`).join('')}</div>`;if(mode==='months')return switcher+cpPanel028('heat','สถานะต้นทุนรายเดือน',cpHeat028(cpAllYearFarms028()),cpHeatTools031(),true);const list=cpRows028();if(mode==='ranking')return switcher+cpPanel028('rank','อันดับต้นทุนรายฟาร์ม · '+Cost028.groups[CP028.group].unit,cpRankPair031(list),'',true);const selected=CP028.colors.length?CP028.colors:['red','orange','yellow','green'],filtered=list.filter(f=>selected.includes(f.category));return switcher+cpPanel028('quadrant','ค่ายา-วัคซีน × ตาย-คัดทิ้ง',cpQuadrant028(list))+cpPanel028('farms','กลุ่มฟาร์มตามสี · '+Cost028.groups[CP028.group].unit,`<p class="cp-muted">กลุ่มสี: ${selected.map(c=>CP_COLOR_NAMES031[c]).join(', ')} · ${filtered.length} ฟาร์ม</p>`+(CP028.table==='list'?cpListTable028(filtered):cpGroupTable028(filtered)),`${cpMulti028('colors','กลุ่มสี',Object.entries(CP_COLOR_NAMES031))}<label>รูปแบบตาราง<select data-cp="table">${cpOptions028([['list','รายชื่อฟาร์ม'],['groups','แยกกลุ่มสี']],CP028.table)}</select></label><label>วิธีเรียง<select data-cp="listOrder">${cpOptions028([['index','ตาม Index'],['color','ตามสี / ตายสูงก่อน']],CP028.listOrder)}</select></label><label>ลำดับ Index<select data-cp="sort">${cpOptions028([['desc','สูง → ต่ำ'],['asc','ต่ำ → สูง']],CP028.sort)}</select></label>${CP028.table==='groups'?`<label>จัดกลุ่มตาม<select data-cp="groupBy">${cpOptions028([['region','ภาค'],['bu','ธุรกิจ']],CP028.groupBy)}</select></label>`:''}`,true);};
function uiCostDrawer032(){const ex=[['unstable','ไม่รวม PRRS: Unstable'],['active','ไม่รวม PRRS: Stable Active'],['PRRS','ไม่รวมเคส PRRS ที่เปิดอยู่'],['D1','ไม่รวมเคส D1 ที่เปิดอยู่']];uiDrawer032('ตัวกรองต้นทุนเพิ่มเติม',`<h3>ประเภทฟาร์ม</h3>${uiChecks032('types',FARM_TYPES023,CP028.types)}<h3>ธุรกิจ</h3>${uiChecks032('bus',[...new Set(CP028.data.rows.map(r=>r.bu))].sort().map(x=>[x,x]),CP028.bus)}<h3>คัดออกตามข้อมูลสุขภาพปัจจุบัน</h3>${uiChecks032('exclude',ex,CP028.exclude)}<label>ชุดเป้าหมาย KPI<select id="uiTarget032">${cpOptions028([[0,'ตามปีที่เลือก'],...Object.keys(CP028.data.kpis).map(y=>[y,'KPI ปี '+(+y+543)])],CP028.targetYear)}</select></label>`,d=>{['types','bus','exclude'].forEach(k=>CP028[k]=uiChecked032(d,k));CP028.targetYear=Number(d.querySelector('#uiTarget032').value);cpDefaults031();cpRender028();});}
function uiCostChart032(el){const key=el.dataset.cpChart,c=cpChartState028(key);c[el.dataset.prop]=el.type==='checkbox'?el.checked:el.value;const p=el.closest('[data-cp-panel]');let group,metric,farm;if(key.startsWith('farm-')){group=CP028.group;metric=key==='farm-trend'?'medvac':key==='farm-dead'?'deadcull':key.slice(5);farm=CP028.farm;}else{group=key.split('-')[0];metric=key.split('-')[1];}if(!['medvac','deadcull'].includes(metric)){cpRender028();return;}const old=p.querySelector(':scope > svg');if(old)old.outerHTML=cpTrend028(group,metric,key,farm);p.querySelector('h2').innerHTML=cpTrendTitle031((farm?'':Cost028.groups[group].label+' · ')+(metric==='medvac'?'ค่ายา-วัคซีน':'ตาย-คัดทิ้ง'),group,metric,key,farm);uiRemember032();}
cpBind028=function(){cpOriginalBind032();$$('[data-cp-farm]').forEach(b=>{b.onclick=()=>{CP028.farm=b.dataset.cpFarm;CP028.search='';CP028.view='farm';cpRender028();};});$$('[data-cp-mode032]').forEach(b=>b.onclick=()=>{CP028.compareMode032=b.dataset.cpMode032;cpRender028();});const more=$('#uiCostMore032');if(more)more.onclick=uiCostDrawer032;$$('[data-clear032]').forEach(b=>b.onclick=()=>{CP028[b.dataset.clear032]=b.dataset.clear032==='targetYear'?0:[];cpDefaults031();cpRender028();});$$('[data-cp-chart]').forEach(el=>el.onchange=()=>uiCostChart032(el));const g=$('[data-cp="group"]');if(g)g.onchange=()=>{CP028.group=g.value;CP028.farm='';cpDefaults031();cpRender028();};if($('#cpResetFilters'))$('#cpResetFilters').onclick=()=>{Object.assign(CP028,{regions:[],bus:[],types:[],exclude:[],targetYear:0,from:1,to:CP028.data.source?.year===CP028.year?CP028.data.source.month:12,search:''});cpDefaults031();cpRender028();};};
cpRender028=function(){if(!window.Cost028){$('#app').innerHTML='<div class="panel">กำลังเปิดโมดูลต้นทุน…</div>';uiShell032();return uiCore032().then(()=>{if(filter==='cost'&&!currentFarm&&!daActive021&&!adminData&&!currentRegion018)cpRender028();}).catch(e=>{if(filter==='cost'){toast(e.message);$('#app').innerHTML='<div class="panel">โหลดโมดูลต้นทุนไม่สำเร็จ <button id="uiRetryCore032">ลองใหม่</button></div>';$('#uiRetryCore032').onclick=cpRender028;uiShell032();}});}if(CP028.data){UI032.costFarms=new Map(CP028.data.farms.map(f=>[f.id,f]));}const out=cpOriginalRender032();if(!$('#app .cp028')){uiShell032();return out;}
 const isAdmin=['import','registry','settings'].includes(CP028.view);$$('[data-cp-view]').forEach(b=>{if(isAdmin||['import','registry','settings'].includes(b.dataset.cpView))b.remove();});if(isAdmin){$('#app h1').textContent=({import:'นำเข้าข้อมูลต้นทุน',registry:'จับคู่ฟาร์ม / รายการรอตรวจ',settings:'ตั้งค่า KPI'})[CP028.view];$('#app .pagehead .cp-muted')?.remove();}
 const exportAll=$('#cpExportAll');if(exportAll)exportAll.parentElement.classList.add('ui-export-choices032');
 $$('[data-cp-panel] .cp-panel-tools').forEach(p=>{if(p.querySelector('[data-cp-chart]'))uiDisplay032(p);else if(p.closest('[data-cp-panel="farms"]')){const keep=p.querySelector('[data-cp-apply="colors"]')?.closest('label');const rest=document.createElement('div');[...p.children].filter(c=>c!==keep).forEach(c=>rest.append(c));p.append(rest);uiDisplay032(rest,'รูปแบบตาราง');}});uiShell032();return out;};
cpFarm028=function(id){return UI032.costFarms?.get(id)||CP028.data.farms.find(f=>f.id===id)||{id,name:'ไม่พบฟาร์ม',region:''};};
const cpOriginalLoad032=cpLoad028;
cpLoad028=async function(){const r=await cpOriginalLoad032();if(filter==='cost'&&!currentFarm&&!daActive021&&!adminData&&!currentRegion018)uiShell032();return r;};
// Farm overview: preserve the existing board/export renderer and compact its controls.
const uiOldDashboard032=dashboard,uiOldVisible032=visibleFarms,uiOldCard032=farmCard,uiOldSnapshot032=overviewSnapshot;
function uiHerdLatest032(farmId,d){return d==='PRRS'?latest(farmId,'prrs'):recs(farmId,'herdStatus').filter(r=>r.data.disease===d).sort((a,b)=>b.data.date.localeCompare(a.data.date)||b.createdAt.localeCompare(a.createdAt))[0];}
visibleFarms=function(){return uiOldVisible032().filter(f=>!(filter==='prrs'&&disease!=='PRRS'&&prrsState)||uiHerdLatest032(f.id,disease)?.data.state===prrsState);};
farmCard=function(f){if(filter==='prrs'&&disease!=='PRRS'){const r=uiHerdLatest032(f.id,disease);return `<button class="farm" data-farm="${esc(f.id)}" title="${esc(r?.data.note||'ยังไม่ระบุสถานะ')}"><span class="farm-label">${esc(farmDisplayName(f))}</span><small class="ui-herd-label032">${esc(r?.data.state||'ยังไม่ระบุสถานะ')}</small></button>`;}return uiOldCard032(f);};
overviewSnapshot=function(){const s=uiOldSnapshot032();s.showPRRS=filter==='prrs'&&disease==='PRRS';return s;};
function uiOverviewDrawer032(){const vets=teamDirectory018.team.filter(t=>t.kind!=='secretary').map(t=>[t.id,t.name]);uiDrawer032('ตัวกรองเพิ่มเติม',`<h3>สัตวแพทย์ผู้รับผิดชอบ</h3>${uiChecks032('vet',vets,values016(selectedVet018))}<label>ข้อมูลที่แสดง<select id="uiFarmKind032">${[['','ทั้งหมด'],['event','โรคระบาด'],['prrs','สถานะฝูง'],['visit','บันทึกเยี่ยมฟาร์ม'],['construction','กำลังก่อสร้าง']].map(([k,l])=>`<option value="${k}" ${filter===k?'selected':''}>${l}</option>`).join('')}</select></label>`,d=>{selectedVet018=uiChecked032(d,'vet').join('|');filter=d.querySelector('#uiFarmKind032').value;prrsView012='region';render();});}
function uiHerdControls032(){const host=$('#app .controls');if(!host||filter!=='prrs')return;host.querySelectorAll('.subfilters').forEach(e=>e.remove());const states=disease==='PRRS'?state.masters.prrs:[...new Set(state.farms.map(f=>uiHerdLatest032(f.id,disease)?.data.state).filter(Boolean))].sort();const row=document.createElement('div');row.className='ui-filterrow032 ui-herd-tools032';row.innerHTML=`<label>โรค<select id="uiHerdDisease032">${['PRRS','PED','FMD'].map(d=>`<option ${disease===d?'selected':''}>${d}</option>`).join('')}</select></label><label>สถานะฝูง<select id="uiHerdState032"><option value="">ทุกสถานะ</option>${states.map(s=>`<option value="${esc(s)}" ${prrsState===s?'selected':''}>${esc(s.replace('FreePRRS','Free PRRS'))}</option>`).join('')}</select></label>${disease==='PRRS'?'<button id="uiByStatus032">By Status</button>':''}`;host.append(row);$('#uiHerdDisease032').onchange=e=>{disease=e.target.value;prrsState='';prrsView012='region';render();};$('#uiHerdState032').onchange=e=>{prrsState=e.target.value;render();};if($('#uiByStatus032'))$('#uiByStatus032').onclick=()=>uiGo032(enterPRRS012);}
dashboard=function(){uiOldDashboard032();if(filter==='prrs'&&disease==='PRRS'&&prrsView012==='status')return;$('#app h1').textContent='ภาพรวมฟาร์ม';const controls=$('#app .controls');if(!controls){uiShell032();return;}
 controls.classList.add('ui-filterbar032');const row=controls.querySelector('.controlrow');row.classList.add('ui-filterrow032');const searchBox=row.querySelector('.search');if(searchBox){const l=document.createElement('label');l.textContent='ค้นหาฟาร์ม';searchBox.before(l);l.append(searchBox);}for(const [id,name] of [['region','ภาค'],['layer','ประเภทฟาร์ม']]){const s=$('#'+id);if(s&&s.parentElement===row){const l=document.createElement('label');l.textContent=name;s.before(l);const multi=s.nextElementSibling;l.append(s);if(multi?.classList.contains('multi016'))l.append(multi);}}
 $('#addFarm')?.remove();$('[data-filter="cost"]')?.remove();$('[data-open-da021]')?.remove();$('#teamFilter018')?.remove();$('#teamChart018')?.remove();controls.querySelectorAll('.subfilters').forEach(e=>{if(e.querySelector('#vet018'))e.remove();});
 const more=document.createElement('button');more.id='uiOverviewMore032';more.className=selectedVet018?'filter-active023':'';more.textContent='ตัวกรองเพิ่มเติม'+(selectedVet018?' · '+values016(selectedVet018).length:'');more.onclick=uiOverviewDrawer032;row.append(more);$('[data-filter="prrs"]').innerHTML=dots+' สถานะฝูง';['visit','construction'].forEach(k=>$(`[data-filter="${k}"]`)?.remove());
 const chips=document.createElement('div');chips.innerHTML=uiChips032([['vet',selectedVet018?'สัตวแพทย์: '+vetNames016():''],['kind',['visit','construction'].includes(filter)?(filter==='visit'?'บันทึกเยี่ยมฟาร์ม':'กำลังก่อสร้าง'):'']]);controls.append(chips);chips.querySelectorAll('[data-clear032]').forEach(b=>b.onclick=()=>{if(b.dataset.clear032==='vet')selectedVet018='';else filter='';render();});
 if(filter==='prrs'&&disease!=='PRRS'){const empty=$('#app > .panel.empty');if(empty){empty.outerHTML=farmBoard(visibleFarms());$$('[data-farm]').forEach(b=>b.onclick=()=>{currentFarm=b.dataset.farm;UI032.herd=disease;tab='prrs';render();window.scrollTo(0,0);});}}
 uiHerdControls032();const event=$('.event-display022');if(event)uiDisplay032(event);uiShell032();};
const uiOldPrDashboard032=prrsDashboard012;
prrsDashboard012=function(){uiOldPrDashboard032();$('#app .pagehead h1').textContent='สถานะฝูง · PRRS';$('#prrsCapture012 h1').textContent='สถานะฝูง PRRS · By Status';$('#app .controls')?.classList.add('ui-filterbar032');$('#prrsRegion012').onclick=()=>uiGo032(()=>{prrsView012='region';render();});uiShell032();};
// All herd status changes are dated, attributed and reasoned; PRRS retains its existing criteria.
function uiHerdForm032(r){const d=r?.data||{};if(state.settings.herdStatusProtocol!==32)return toast('กรุณาอัปเดต Code.gs และ Deploy รุ่นใหม่ก่อนบันทึกสถานะ PED/FMD');modal('บันทึกสถานะฝูง '+UI032.herd,formWrap(field('วันที่มีผล','date',d.date||today(),'date')+field('สถานะที่สัตวแพทย์ระบุ','state',d.state||'')+`<label class="field full">เหตุผล / ข้อมูลประกอบ<textarea name="note" required maxlength="4000">${esc(d.note||'')}</textarea></label>`));$('#form').onsubmit=e=>formSubmit(e,v=>api('saveRecord',{farmId:currentFarm,type:'herdStatus',id:r?.id,revision:r?.revision,data:{...v,disease:UI032.herd}}));paRecovery024('herdStatus');}
function uiHerdPanel032(target){const d=UI032.herd,records=recs(currentFarm,'herdStatus',true).filter(r=>r.data.disease===d).sort((a,b)=>b.data.date.localeCompare(a.data.date)||b.createdAt.localeCompare(a.createdAt));target.innerHTML=`<section class="panel"><div class="panelhead"><h2>สถานะฝูง ${d}</h2>${editable()?'<button id="uiNewHerd032" class="primary">+ บันทึกสถานะ</button>':''}</div><p>สถานะล่าสุด: <strong>${esc(uiHerdLatest032(currentFarm,d)?.data.state||'ยังไม่ระบุสถานะ')}</strong></p><div class="tablewrap"><table><thead><tr><th>วันที่มีผล</th><th>สถานะฝูง</th><th>เหตุผล</th><th>ผู้บันทึก</th><th></th></tr></thead><tbody>${records.map(r=>`<tr class="${r.status==='CANCELLED'?'cancelled':''}"><td>${esc(thai(r.data.date))}</td><td>${esc(r.data.state)}${r.status==='CANCELLED'?' (ยกเลิก)':''}</td><td>${esc(r.data.note)}</td><td>${esc(r.data.by)}</td><td>${editable()&&r.status==='ACTIVE'?`<button data-herd-edit032="${esc(r.id)}">แก้ไข</button> <button data-cancel="${esc(r.id)}">ยกเลิก</button>`:''}</td></tr>`).join('')}</tbody></table></div>${records.length?'':'<p class="muted">ยังไม่มีประวัติสถานะฝูงของโรคนี้</p>'}</section>`;if($('#uiNewHerd032'))$('#uiNewHerd032').onclick=()=>uiHerdForm032();$$('[data-herd-edit032]').forEach(b=>b.onclick=()=>uiHerdForm032(records.find(r=>r.id===b.dataset.herdEdit032)));$$('[data-cancel]').forEach(b=>b.onclick=()=>cancelForm(state.records.find(r=>r.id===b.dataset.cancel)));}
const uiOldDetail032=detail,uiOldRenderPRRS032=renderPRRS024;
renderPRRS024=function(target){if(UI032.herd==='PRRS')uiOldRenderPRRS032(target);else uiHerdPanel032(target);const row=document.createElement('div');row.className='ui-herd-picker032';row.innerHTML=`<label>สถานะฝูงต่อโรค <select id="uiDetailDisease032">${['PRRS','PED','FMD'].map(d=>`<option ${UI032.herd===d?'selected':''}>${d}</option>`).join('')}</select></label>`;target.prepend(row);$('#uiDetailDisease032').onchange=e=>{UI032.herd=e.target.value;ppView026.id='';render();};const toolbar=$('.pa-toolbar024');if(toolbar){const opts=document.createElement('div');opts.className='ui-herd-options032';['#paGaps024','#paPCR025'].forEach(id=>{const el=$(id)?.closest('label');if(el)opts.append(el);});toolbar.append(opts);uiDisplay032(opts);}uiShell032();};
detail=function(){uiOldDetail032();uiShell032();};
// Disease analytics: shared scope, locally relevant controls and cached navigation.
const uiOldDAFilter032=daFilterUI021,uiOldDARender032=daRender021,uiOldDAContent032=daContent021;
DA_TABS021.splice(0,DA_TABS021.length,['overview','ภาพรวม'],['map','แผนที่'],['year','รายปี'],['disease','รายโรค'],['farm','รายฟาร์ม'],['loss','ความเสียหาย'],['rules','เกณฑ์ราคา']);
daContent021=function(events){return daView021==='year'?daMatrix021(events)+daTrend021(events):uiOldDAContent032(events);};
daFilterUI021=function(){const all=daData021.events,more=daFilters021.layers.length+daFilters021.farms.length+daFilters021.statuses.length+(daPrice021!=='period'?1:0);return `<div class="panel da-filters021 ui-filterbar032"><div class="ui-filterrow032">${daMulti021('years','ปี',daUnique021(all.map(e=>e.date.slice(0,4))).map(y=>[y,Number(y)+543+' ('+y+')']))}${daMulti021('diseases','ชื่อโรค',daUnique021(all.map(e=>e.disease)).map(x=>[x,x]))}${daMulti021('regions','ภาค',daUnique021(all.map(e=>e.region)).map(x=>[x,x]))}<button id="uiDAMore032" class="${more?'filter-active023':''}">ตัวกรองเพิ่มเติม${more?' · '+more:''}</button><button id="daReset021" class="ui-text032">ล้างตัวกรอง</button></div>${uiChips032([['layers',daFilters021.layers.map(k=>FARM_TYPES023.find(t=>t[0]===k)?.[1]||k).join(', ')],['farms',daFilters021.farms.map(id=>daFarm021(id)?.name||id).join(', ')],['statuses',daFilters021.statuses.map(k=>DA_STATUS021[k]||k).join(', ')],['price',daPrice021!=='period'?'จำลองราคา: '+(daData021.rules.find(r=>r.id===daPrice021)?.name||''):'']])}</div>`;};
function uiDADrawer032(){const d=uiDrawer032('ตัวกรองข้อมูลการเกิดโรค',`<h3>ประเภทฟาร์ม</h3>${uiChecks032('layers',FARM_TYPES023,daFilters021.layers)}<h3>ฟาร์มที่มีประวัติโรค</h3><input type="search" id="uiDAFarmSearch032" placeholder="พิมพ์ค้นหาชื่อฟาร์ม" aria-label="ค้นหาฟาร์ม">${uiChecks032('farms',daFarmChoices022(),daFilters021.farms)}<h3>สถานะเคส</h3>${uiChecks032('statuses',Object.entries(DA_STATUS021),daFilters021.statuses)}<label>เกณฑ์มูลค่า<select id="uiDAPrice032"><option value="period">ตามวันที่เกิดเคส</option>${daData021.rules.slice().reverse().map(r=>`<option value="${esc(r.id)}" ${daPrice021===r.id?'selected':''}>จำลอง: ${esc(r.name)}</option>`).join('')}</select></label>`,el=>{['layers','farms','statuses'].forEach(k=>daFilters021[k]=uiChecked032(el,k));daPrice021=el.querySelector('#uiDAPrice032').value;daPruneFarms022();daRender021();});d.querySelector('#uiDAFarmSearch032').oninput=e=>{const q=e.target.value.toLocaleLowerCase('th');d.querySelectorAll('[data-check032="farms"]').forEach(i=>i.parentElement.hidden=!i.parentElement.textContent.toLocaleLowerCase('th').includes(q));};}
daRender021=function(){uiOldDARender032();if(!$('#daCapture021'))return;$$('[data-da-tab021="rules"]').forEach(b=>b.remove());if(daView021==='rules'&&state.user.role!=='Admin'){daView021='overview';return daRender021();}if(daView021==='rules')$('#app > .tabs')?.remove();const price=$('#daPrice021');price?.closest('label')?.remove();if($('#uiDAMore032'))$('#uiDAMore032').onclick=uiDADrawer032;$$('.da-filters021 [data-clear032]').forEach(b=>b.onclick=()=>{if(b.dataset.clear032==='price')daPrice021='period';else daFilters021[b.dataset.clear032]=[];daPruneFarms022();daRender021();});if($('#daReset021'))$('#daReset021').onclick=()=>{Object.keys(daFilters021).forEach(k=>daFilters021[k]=[]);daPrice021='period';daRender021();};uiShell032();};
openAnalytics021=async function(farmId){daActive021=true;adminData=null;currentRegion018=null;currentFarm=null;if(farmId){daFilters021={years:[],diseases:[],regions:[],layers:[],farms:[farmId],statuses:[]};daView021='farm';}if(daData021)daRender021();else{const p=daLoad021();uiShell032();await p;uiShell032();}};
const uiOldRegion032=regionView018;
regionView018=function(){uiOldRegion032();if(currentRegion018==='ALL')$('#app .pagehead h1').textContent='ทีมงานสัตวแพทย์';uiShell032();};
// Administration is a separate destination, with all original permission checks retained.
const uiOldAdmin032=renderAdmin;
function uiAdminCost032(view){uiGo032(()=>{adminData=null;daActive021=false;currentRegion018=null;currentFarm=null;filter='cost';CP028.view=view;render();});}
renderAdmin=function(){if(state.user.role!=='Admin'){adminData=null;return render();}UI032.adminCache=adminData;if(UI032.adminView==='team'&&management019){drawManagement019(UI032.teamSelected||'');return;}if(UI032.adminView==='users'){uiOldAdmin032();uiShell032();return;}const pending=CP028.data?.display?.pendingCount;$('#app').innerHTML=`<div class="pagehead"><div><div class="eyebrow">SVS ADMINISTRATION</div><h1>จัดการระบบ</h1></div></div><div class="ui-admin-grid032"><section class="panel"><h2>ข้อมูลต้นทุน</h2><p class="muted">นำเข้ารายเดือน ตรวจคู่ฟาร์ม และตั้งเป้าหมาย</p><button data-admin-cost032="import">นำเข้าข้อมูล</button><button data-admin-cost032="registry">จับคู่ฟาร์ม / รายการรอตรวจ${pending!=null?' · '+pending:''}</button><button data-admin-cost032="settings">ตั้งค่า KPI</button></section><section class="panel"><h2>ทะเบียนฟาร์มและผู้ใช้</h2><p class="muted">ดูแลข้อมูลฟาร์ม บัญชี และการมอบหมายงาน</p><button id="uiFarmRegistry032">ทะเบียนฟาร์ม</button><button id="uiUsers032">ผู้ใช้และสิทธิ์</button><button id="uiTeamAdmin032">ทีมและผู้รับผิดชอบ</button></section><section class="panel"><h2>ข้อมูลการเกิดโรค</h2><p class="muted">ตั้งเกณฑ์มูลค่าความเสียหาย</p><button id="uiDiseaseRules032">เกณฑ์ราคา</button></section></div>`;$$('[data-admin-cost032]').forEach(b=>b.onclick=()=>uiAdminCost032(b.dataset.adminCost032));$('#uiUsers032').onclick=()=>uiGo032(()=>{UI032.adminView='users';renderAdmin();});$('#uiTeamAdmin032').onclick=()=>uiGo032(showTeamManagement019);$('#uiFarmRegistry032').onclick=()=>uiGo032(()=>{UI032.adminView='farms';uiFarmRegistry032();});$('#uiDiseaseRules032').onclick=()=>uiGo032(()=>{daView021='rules';openAnalytics021();});if(UI032.adminView==='farms')return uiFarmRegistry032();uiShell032();};
function uiFarmRegistry032(){if(state.user?.role!=='Admin')return;$('#app').innerHTML=`<div class="pagehead"><h1>ทะเบียนฟาร์ม</h1><button id="uiAddFarm032" class="primary">+ เพิ่มฟาร์ม</button></div><div class="panel"><label>ค้นหาชื่อฟาร์ม<input type="search" id="uiRegistrySearch032" placeholder="พิมพ์ชื่อฟาร์ม"></label><div class="tablewrap"><table><thead><tr><th>ชื่อฟาร์ม</th><th>ภาค</th><th>ประเภท</th><th>GDU</th><th></th></tr></thead><tbody>${state.farms.slice().sort(farmSort010).map(f=>`<tr data-registry-name032="${esc(f.name.toLocaleLowerCase('th'))}"><td>${esc(f.name)}</td><td>${esc(f.region)}</td><td>${esc(farmTypeLabel023(f))}</td><td>${f.gdu==='true'?'มี':'ไม่มี'}</td><td><button data-registry-edit032="${esc(f.id)}">แก้ไข</button><button data-registry-open032="${esc(f.id)}">เปิดฟาร์ม</button></td></tr>`).join('')}</tbody></table></div></div>`;$('#uiAddFarm032').onclick=()=>farmForm();$('#uiRegistrySearch032').oninput=e=>{$$('[data-registry-name032]').forEach(r=>r.hidden=!r.dataset.registryName032.includes(e.target.value.toLocaleLowerCase('th')));};$$('[data-registry-edit032]').forEach(b=>b.onclick=()=>farmForm(state.farms.find(f=>f.id===b.dataset.registryEdit032)));$$('[data-registry-open032]').forEach(b=>b.onclick=()=>uiGo032(()=>{adminData=null;filter='';currentFarm=b.dataset.registryOpen032;tab='profile';render();}));uiShell032();}
const uiOldManagement032=drawManagement019;
drawManagement019=function(selected=''){UI032.adminView='team';UI032.teamSelected=selected;uiOldManagement032(selected);uiShell032();};
const uiOldLogin032=loginView;
loginView=function(message=''){UI032.run=Date.now().toString(36)+Math.random().toString(36).slice(2);UI032.uid='';UI032.entries=[];UI032.at=-1;UI032.adminCache=null;UI032.costFarms=null;document.querySelector('header nav').innerHTML='<button id="home" hidden></button><button id="admin" hidden></button>';return uiOldLogin032(message);};
const uiOldSnapshotCP032=cpSnapshotUI028;
cpSnapshotUI028=function(){const c=uiOldSnapshotCP032();c.querySelectorAll('.ui-screen032,.ui-chips032').forEach(e=>e.remove());return c;};
// Dismiss menus by Escape/outside click without discarding selected filters.
document.addEventListener('click',e=>{document.querySelectorAll('.ui-export032[open],.ui-display032[open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.ui-export032[open],.ui-display032[open]').forEach(d=>d.open=false);});
// Normalize laboratory controls without affecting their table or export logic.
const uiOldLab032=renderLab;
renderLab=function(target){uiOldLab032(target);const row=target.querySelector('.panelhead .controlrow');if(row){row.classList.add('ui-filterrow032');for(const [id,name] of [['labSample017','ประเภทตัวอย่าง'],['labYear','ปี']]){const el=$('#'+id);if(el){const label=document.createElement('label');label.textContent=name;el.before(label);const multi=el.nextElementSibling;label.append(el);if(multi?.classList.contains('multi016'))label.append(multi);}}const seg=row.querySelector('.segmented');if(seg)uiDisplay032(seg); }uiShell032();};
// Started after map module.
