const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync('backend/Code.gs','utf8');
function env(){
 const cache=new Map(),db={Users:[],Farms:[{id:'farm1',name:'A'},{id:'farm2',name:'B'}],Assignments:[{id:'as1',farmId:'farm1',userId:'op1',endAt:''},{id:'as2',farmId:'farm1',userId:'op2',endAt:''}],Records:[],Files:[],Audit:[]};
 const ctx={console,PropertiesService:{getScriptProperties:()=>({getProperty:()=>null})},Utilities:{getUuid:()=>crypto.randomUUID(),computeDigest:(_,s)=>Array.from(crypto.createHash('sha256').update(s).digest()),base64EncodeWebSafe:a=>Buffer.from(a).toString('base64url'),DigestAlgorithm:{SHA_256:'sha256'}},CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})}};
 vm.createContext(ctx);vm.runInContext(source,ctx);const schema=vm.runInContext('SCHEMA',ctx);ctx.rows=t=>(db[t]||[]).map((r,i)=>({...Object.fromEntries(schema[t].map(k=>[k,String(r[k]??'')])),_row:i+2}));ctx.write=(t,r)=>{let i=(db[t]||[]).findIndex(x=>x.id===r.id);if(i<0)db[t].push({...r});else db[t][i]={...r};};ctx.audit=()=>{};
 const op={id:'op1',name:'สัตวแพทย์หนึ่ง',role:'Operation',status:'ACTIVE'},op2={id:'op2',name:'สัตวแพทย์สอง',role:'Operation',status:'ACTIVE'},management={id:'m1',role:'Management',status:'ACTIVE'},admin={id:'a1',role:'Admin',status:'ACTIVE',email:'admin@example.org'};db.Users=[op,op2,management,admin];return {ctx,db,cache,op,op2,management,admin};
}
function event(){return {farmId:'farm1',type:'event',data:{disease:'PRRS',unit:'Farrowing',detectedAt:'2026-09-09',affected:10,loss:2}};}
test('Operation cannot write another farm',()=>{const e=env(),p=event();p.farmId='farm2';assert.throws(()=>e.ctx.saveRecord(e.op,p),/ไม่มีสิทธิ์/);});
test('Management cannot create records',()=>{const e=env();assert.throws(()=>e.ctx.saveRecord(e.management,event()),/ดูข้อมูล/);});
test('Operation data reads exclude unassigned farms',()=>{const e=env();e.ctx.saveRecord(e.admin,{...event(),farmId:'farm2'});assert.equal(e.ctx.readRecords(e.op).length,0);});
test('Draft is only visible to creator, including exclusion for Admin',()=>{const e=env();e.ctx.saveRecord(e.op,{farmId:'farm1',type:'visit',status:'DRAFT',data:{issues:[]}});assert.equal(e.ctx.readRecords(e.op).length,1);assert.equal(e.ctx.readRecords(e.op2).length,0);assert.equal(e.ctx.readRecords(e.admin).length,0);});
test('Other assigned vet cannot modify private draft',()=>{const e=env();const r=e.ctx.saveRecord(e.op,{farmId:'farm1',type:'visit',status:'DRAFT',data:{issues:[]}});assert.throws(()=>e.ctx.saveRecord(e.op2,{id:r.id,revision:r.revision,farmId:'farm1',type:'visit',data:{issues:[]}}),/ผู้สร้าง/);});
test('Final visit requires at least one complete issue',()=>{const e=env();assert.throws(()=>e.ctx.saveRecord(e.op,{farmId:'farm1',type:'visit',data:{date:'2026-09-09',issues:[]}}),/อย่างน้อย/);});
test('Other is a valid Visit category',()=>{const e=env();const r=e.ctx.saveRecord(e.op,{farmId:'farm1',type:'visit',data:{date:'2026-09-09',issues:[{category:'Other',finding:'พบข้อมูล',advice:'คำแนะนำ',images:[]}]}});assert.equal(r.data.issues[0].category,'Other');});
test('Visit rejects more than two images',()=>{const e=env();assert.throws(()=>e.ctx.saveRecord(e.op,{farmId:'farm1',type:'visit',data:{date:'2026-09-09',issues:[{category:'Other',finding:'a',advice:'b',images:['1','2','3']}]}}),/2 รูป/);});
test('Assigned replacement vet may edit active record, preserving author',()=>{const e=env(),r=e.ctx.saveRecord(e.op,event());const next=e.ctx.saveRecord(e.op2,{...event(),id:r.id,revision:r.revision,data:{...event().data,affected:12}});assert.equal(next.createdBy,'op1');assert.equal(next.updatedBy,'op2');assert.equal(next.data.history.length,2);assert.equal(next.data.affected,12);});
test('Reject stale revision to prevent overwriting concurrent edits',()=>{const e=env(),r=e.ctx.saveRecord(e.op,event());assert.throws(()=>e.ctx.saveRecord(e.op,{...event(),id:r.id,revision:0}),/ผู้อื่น/);});
test('Negative counts and fractional counts rejected',()=>{const e=env();for(const x of [-1,1.5])assert.throws(()=>e.ctx.saveRecord(e.op,{...event(),data:{...event().data,affected:x}}),/จำนวนเต็ม/);});
test('Invalid calendar date rejected',()=>{const e=env();assert.equal(e.ctx.dateOK('2026-02-30'),false);});
test('Close event requires explicit confirmation',()=>{const e=env(),r=e.ctx.saveRecord(e.op,event());assert.throws(()=>e.ctx.saveRecord(e.op,{...event(),id:r.id,revision:r.revision,data:{...event().data,closedAt:'2026-09-10'}}),/ยืนยัน/);});
test('Closing preserves active record and history',()=>{const e=env(),r=e.ctx.saveRecord(e.op,event());const c=e.ctx.saveRecord(e.op,{...event(),id:r.id,revision:r.revision,confirmClose:true,data:{...event().data,closedAt:'2026-09-10'}});assert.equal(c.status,'ACTIVE');assert.equal(c.data.closedAt,'2026-09-10');assert.equal(c.data.history.length,2);});
test('Closed events cannot be silently reopened',()=>{const e=env();const r=e.ctx.saveRecord(e.op,{...event(),confirmClose:true,data:{...event().data,closedAt:'2026-09-10'}});assert.throws(()=>e.ctx.saveRecord(e.op,{...event(),id:r.id,revision:r.revision}),/เคสปิด/);});
test('Lab rejects unapproved result states',()=>{const e=env();assert.throws(()=>e.ctx.saveRecord(e.op,{farmId:'farm1',type:'lab',data:{sample:'Water',date:'2026-09-09',result:'Positive'}}),/ผลตรวจ/);});
test('Lab keeps all entries in same month without aggregation',()=>{const e=env();for(const result of ['Pass','NotPass'])e.ctx.saveRecord(e.op,{farmId:'farm1',type:'lab',data:{sample:'Water',date:'2026-09-09',result}});assert.equal(e.db.Records.length,2);});
test('PRRS labels exact and no invented PED state',()=>{const e=env();for(const state of ['Unstable','Stable Active','Stable Inactive','FreePRRS'])e.ctx.saveRecord(e.op,{farmId:'farm1',type:'prrs',data:{date:'2026-09-09',state}});assert.equal(e.db.Records.length,4);assert.throws(()=>e.ctx.saveRecord(e.op,{farmId:'farm1',type:'prrs',data:{date:'2026-09-09',state:'FreePED'}}));});
test('Cancellation Other requires reason detail and retains record',()=>{const e=env(),r=e.ctx.saveRecord(e.op,event());assert.throws(()=>e.ctx.cancelRecord(e.op,{id:r.id,revision:r.revision,reason:'อื่นๆ'}));e.ctx.cancelRecord(e.op,{id:r.id,revision:r.revision,reason:'รายการซ้ำ'});assert.equal(e.db.Records.length,1);assert.equal(e.db.Records[0].status,'CANCELLED');});
test('Inactive user denied even with existing session',()=>{const e=env(),t='12345678901234567890123456789';e.cache.set('s:'+e.ctx.sha(t),JSON.stringify({uid:'op1'}));e.db.Users[0].status='INACTIVE';assert.throws(()=>e.ctx.session(t),/ไม่ได้รับอนุญาต/);});
test('Ending assignment revokes next read immediately',()=>{const e=env();e.ctx.saveRecord(e.op,event());e.db.Assignments[0].endAt=new Date().toISOString();assert.equal(e.ctx.readRecords(e.op).length,0);});
test('Admin cannot deactivate the last active admin',()=>{const e=env();assert.throws(()=>e.ctx.saveUser(e.admin,{data:{id:'a1',name:'Admin',email:'admin@example.org',role:'Admin',status:'INACTIVE'}}),/ต้องเหลือ Admin/);});
test('Duplicate login emails rejected case-insensitively',()=>{const e=env();assert.throws(()=>e.ctx.saveUser(e.admin,{data:{name:'Other',email:'ADMIN@example.org',role:'Operation',status:'ACTIVE'}}),/อีเมลซ้ำ/);});
test('Unauthorised file access is denied before Drive lookup',()=>{const e=env();e.db.Files.push({id:'file1',farmId:'farm2',recordId:'r',owner:'a1'});assert.throws(()=>e.ctx.readFile(e.op,{id:'file1'}),/ไม่มีสิทธิ์/);});
